### ISSUE TITLE
Node Red Doesn't load with 1.0.6

### ISSUE THREAD

**Issue by cdn4lf** [zachowj/hass-node-red#106]
## Version of the custom_component

1.0.6

## Configuration
Unsure what to include.  Integration installed through HACS and enabled through UI.  Running HA Container, 2021.12.8

```yaml

Add your logs here.

```

## Describe the bug

Integration doesn't load with HACS custom component version 1.0.6

## Debug log

```2022-01-08 15:32:00 ERROR (MainThread) [homeassistant.setup] Setup failed for nodered: Integration not found.



```

**Comment by cdn4lf** [comment]
Once I reverted to 1.0.5, everything is working.

**Comment by bmorgan99** [comment]
I was getting "Node-RED custom integration needs to be installed in Home Assistant for this node to function correctly" with 1.0.6.  Rebooted a second time and error gone.

**Comment by cdn4lf** [comment]
I'd rebooted twice, no change.  Reverting got it working on first boot.

**Comment by bmorgan99** [comment]
Oh, also reloaded 1.0.6 first.

**Comment by cdn4lf** [comment]
Reload / Reverting down and up worked to get it going again.
