### ISSUE TITLE
Nodered integration missing

### ISSUE THREAD

**Issue by PrathikGopal** [zachowj/hass-node-red#107]
Solution below: https://github.com/zachowj/hass-node-red/issues/107#issuecomment-1008233688

Running latest HA and websocket versions 
Installation through hacs
Tried reloading/rebooting.
Tried downgrading to 1.0.5 - same issue.
Tried other suggestions in the closed issues- no go!
Found the custom integration is being loaded in the home-assistant.log but integration missing in UI

## Version of the custom_component
1.0.6

## Describe the bug
Integration for nodered missing after update to 1.0.6. 
first there was an error to load component so I deleted it to re-add but when I tried to add through integration nodered was missing

**Comment by TTLucian** [comment]
Same here. NodeRed missing
```
Logger: homeassistant.setup
Source: setup.py:153
First occurred: 05:17:53 (1 occurrences)
Last logged: 05:17:53

Setup failed for nodered: Integration not found.
```

**Comment by mikesn31** [comment]
Same here no Node-Red afyer upgrade.. restored from snapshot until this gets fixed 👍

**Comment by TTLucian** [comment]
Redownload 1.05 from HACS worked for me.

**Comment by PrathikGopal** [comment]
Solution Update: 
So, once your unable to find the integration.

1. Ensure add on is in the correct path under custom components. I found the path in the custom components was messed up somehow. Deleted the integration and reinstalled 1.0.6 again.

Ensure the integration loads in the ha logs..
 
2. Goto the integration page and refresh the page- In my case from phone I had to pull down to refresh. 

Once done voila it showed nodered companion integration again in the integrations page. 

Seems like a refresh bug to me in HA.

**Comment by dolenec** [comment]
Same for me.. 1.0.5 working.. 1.0.6 break Node-RED..

**Comment by regevbr** [comment]
Same thing happend to me, looking at the commits i can't see anything that should have caused this issue... @zachowj do you mind taking a look at this issue?

**Comment by hklages** [comment]
same problem with 1.06 here
Installing v.1.05 from integration pages solved the problem.

**Comment by Mangomc** [comment]
Deleting and reinstalling 1.0.6 solved it for me

**Comment by zachowj** [comment]
Between this issue and #106, it sounds like an install issue. Is everyone installing it via HACS? Can someone who hasn't deleted and reinstalled check the install location `custom_components/nodered` and see if all the files are being installed in the correctly?

**Comment by alsFC** [comment]
Same here. Rollback to 1.0.5 works.

**Comment by ianfretwell** [comment]
Updated via HACS. Currently in a 'broken' state.

Inside custom components I'm seeing a nodered folder within a nodered folder.  The top level one contains just the one file:-  '__init__.py'. The nodered subfolder then seems to contain all the files I'd expect to see except the '__pycache__' folder.

Does that help ?

**Comment by zachowj** [comment]
@ianfretwell If you have HACS redownload it does it fix the folder structure? There should only be one nodered directory. If that doesn't fix it if you remove the integration from HACS then re-add it does it download into the correct folders?

**Comment by ianfretwell** [comment]
@zachowj Hi - yes, that's cleaned it all up and upon restarting HA it's working again just fine. Thanks!

**Comment by robertboccia** [comment]
> @ianfretwell If you have HACS redownload it does it fix the folder structure? There should only be one nodered directory. If that doesn't fix it if you remove the integration from HACS then re-add it does it download into the correct folders?

Tried re-download, Hasnt helped,  any other ideas

**Comment by robertboccia** [comment]
Just redownloaded again done  and it's resolved the issue

**Comment by modem** [comment]
Issue seems to be HACS related: https://github.com/hacs/integration/issues/2437

**Comment by TTLucian** [comment]
Latest HACS update seems to solve the issue.

**Comment by PrathikGopal** [comment]
Issue resolved with HACS update.
