### ISSUE TITLE
Install without HACS ?

### ISSUE THREAD

**Issue by xstable** [zachowj/hass-node-red#109]
I've only seen the instructions, that the package is available in HACS. Is there a way to install it in a general HA, without the need of HACS too?
Why isn't this module provided in AddOn & Software kategory of HA?

**Comment by zachowj** [comment]
Installation instructions are provided in the README.

<https://github.com/zachowj/hass-node-red#installation>

**Comment by xstable** [comment]
Thank you for your answer. I've read this, but for me it looks like, that I first have to install the component via HACS, and after this I have to run through those described steps, right?

The question is, how can I install it without the need for HACS?

Am 9. Januar 2022 21:25:08 MEZ schrieb Jason ***@***.***>:
>Installation instructions are provided in the README.
>
><https://github.com/zachowj/hass-node-red#installation>
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/zachowj/hass-node-red/issues/109#issuecomment-1008367939
>You are receiving this because you authored the thread.
>
>Message ID: ***@***.***>
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by zachowj** [comment]
No those directions are to install it manually without HACS.

**Comment by xstable** [comment]
Ok, thank you. Then the part is missing, how does the sourcecodes come to my HA.
I mean something like: Download the package to folder `xy` or an example `wget command` to do this.

**Comment by prof7bit** [comment]
Is it planned to apply for first class citizenship in HA and become part of the "standard" integrations that are available with a stock install? It would be incredibly awesome if after installing the Node-RED add-on it would automatically detect its presence (like it automatically detects other connected devices) and just pop up there in the integrations list, ready to be used. This would be beyond awesome. Please make it happen!
