### ISSUE TITLE
node-RED integrations don't work with node-RED

### ISSUE THREAD

**Issue by EkielZan** [zachowj/hass-node-red#11]
Hi,

I'm having issues with the nodered custom integration for Home assistant.
When i try to add the integrations no text is displayed for the node red integrations:

![image](https://user-images.githubusercontent.com/7491931/74317212-41e40480-4d7b-11ea-9f70-8329136dca2b.png)

When "configured" it look like this in the integrations list :

![image](https://user-images.githubusercontent.com/7491931/74317279-66d87780-4d7b-11ea-9a16-18140b9ca713.png)

And in node-red, I've a error message whn i try to use the sensor component: 

![image](https://user-images.githubusercontent.com/7491931/74317361-925b6200-4d7b-11ea-8124-fed4465d805a.png)
![image](https://user-images.githubusercontent.com/7491931/74317406-a7d08c00-4d7b-11ea-96d8-d1efd60a6e90.png)

I've restarted many time and reinstalled many time and nothing change.

I'm using hass.io ( docker containers )

Regards,
Gilles aka Ekiel

**Comment by maracana42** [comment]
> Hi,
> 
> I'm having issues with the nodered custom integration for Home assistant.
> When i try to add the integrations no text is displayed for the node red integrations:
> 
> ![image](https://user-images.githubusercontent.com/7491931/74317212-41e40480-4d7b-11ea-9f70-8329136dca2b.png)
> 
> When "configured" it look like this in the integrations list :
> 
> ![image](https://user-images.githubusercontent.com/7491931/74317279-66d87780-4d7b-11ea-9a16-18140b9ca713.png)
> 
> And in node-red, I've a error message whn i try to use the sensor component:
> 
> ![image](https://user-images.githubusercontent.com/7491931/74317361-925b6200-4d7b-11ea-8124-fed4465d805a.png)
> ![image](https://user-images.githubusercontent.com/7491931/74317406-a7d08c00-4d7b-11ea-96d8-d1efd60a6e90.png)
> 
> I've restarted many time and reinstalled many time and nothing change.
> 
> I'm using hass.io ( docker containers )
> 
> Regards,
> Gilles aka Ekiel

Hello,

I have the same issue.  Home assistant don't see the integration.

**Comment by zachowj** [comment]
Did you install the integration from HACS? I saw that there was an issue installing things that had subdirectories, that is now fixed. Try checking the `custom_component/nodered` directory to see if there's a folder `.translations`.

**Comment by EkielZan** [comment]
i update the hacs version, and no i don't have it :

![image](https://user-images.githubusercontent.com/7491931/74426581-eaff2d80-4e55-11ea-9d21-93d5216eb352.png)

**Comment by MTrab** [comment]
Reinstall the Node-Red integration. I had same error.

**Comment by EkielZan** [comment]
Yes indeed.I removed it and reinstall and now i've the .translation

**Comment by EkielZan** [comment]
And nove a sensor appeart in the integration ! Thanks guys. 
Love the HA community.

**Comment by maracana42** [comment]
> Did you install the integration from HACS? I saw that there was an issue installing things that had subdirectories, that is now fixed. Try checking the `custom_component/nodered` directory to see if there's a folder `.translations`.

Thank guy!!!
