### ISSUE TITLE
Add the ability to update the Icon of Entity Node

### ISSUE THREAD

**Issue by TEF2one** [zachowj/hass-node-red#118]
**Issue**
When changing an entity state it would be nice to also be able to change the entity icon according to the state.
For example, I have some template switch that I use to control a gate then sending whether the gate is opened or closed dit displays relative icon,

**Feature*
It would be great if the input of the entity node could receive the name of the icon to be used such as:
msg.icon could be set to "mdi:gate-open" then sent to the entity node to be updated.

**Alternatives**
Alternatively, it would be nice to be able to configure separate icons for each possible state of an entity.

**Additional context**
For reference here is a [Reddit](https://www.reddit.com/r/homeassistant/comments/sj3u6k/nodered_entity_node_icon_config/
) thread related to the feature request.

**Comment by zachowj** [comment]
It's not supported but it is possible. You will need to replace the SERVER_ID and NODE_ID with the correct values from the entity switch node. They can be found when the node is selected in the information tab.

![image](https://user-images.githubusercontent.com/37859597/152434763-b1a7b432-494b-416c-8da7-333ed7ce520a.png)

```
[{"id":"bb5f2279cbdc66e7","type":"server-state-changed","z":"894a6b3077af9604","name":"","server":"","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.gate_opener_contact","entityidfiltertype":"exact","outputinitially":false,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[],"x":306,"y":1440,"wires":[["367db4c96c25269f"]]},{"id":"367db4c96c25269f","type":"ha-api","z":"894a6b3077af9604","name":"","server":"","version":1,"debugenabled":true,"protocol":"websocket","method":"get","path":"","data":"{\t    \"type\": \"nodered/discovery\",\t    \"server_id\": \"SERVER_ID\",\t    \"node_id\": \"NODE_ID\",\t    \"component\": 'switch',\t    \"config\": {\t        \"name\": \"Gate Control\",\t        \"icon\": $entities(\"binary_sensor.gate_opener_contact\").state = \"off\" ? \"mdi:gate-open\" : \"mdi:gate\"\t    }\t}","dataType":"jsonata","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":594,"y":1440,"wires":[[]]}]
```

**Comment by TEF2one** [comment]
@zachowj , oh that is a nice workaround, I didn't we could do things like that.

**Comment by TEF2one** [comment]
@zachowj I just notice a side effect to the workaround, yes it does change the icon but then if I try to toggle the switch from Lovelace it then goes to unavailable.
![image](https://user-images.githubusercontent.com/20015656/152603500-ae22b23b-14fc-4a0f-b180-a84dcc866d4a.png)


>`[{"id":"6d82955b97bc34e1","type":"ha-entity","z":"dcb46f81965b861b","name":"Button","server":"8093ca4.46eb138","version":2,"debugenabled":false,"outputs":2,"entityType":"switch","config":[{"property":"name","value":"Gate Control"},{"property":"device_class","value":""},{"property":"icon","value":"mdi:gate"},{"property":"unit_of_measurement","value":""},{"property":"state_class","value":""},{"property":"last_reset","value":""}],"state":"payload","stateType":"msg","attributes":[],"resend":true,"outputLocation":"payload","outputLocationType":"none","inputOverride":"allow","outputOnStateChange":true,"outputPayload":"$entity().state ? \"on\": \"off\"","outputPayloadType":"jsonata","x":430,"y":160,"wires":[["48b28d70ea3fa86c","405ea8184aa08c9f","48b28d70ea3fa86c","405ea8184aa08c9f","48b28d70ea3fa86c","405ea8184aa08c9f"],["48b28d70ea3fa86c","405ea8184aa08c9f","48b28d70ea3fa86c","405ea8184aa08c9f","48b28d70ea3fa86c","405ea8184aa08c9f"]]},{"id":"e83ae7944c91682c","type":"server-state-changed","z":"dcb46f81965b861b","name":"status","server":"8093ca4.46eb138","version":3,"exposeToHomeAssistant":false,"haConfig":[{"property":"name","value":""},{"property":"icon","value":""}],"entityidfilter":"binary_sensor.gate_opener_contact","entityidfiltertype":"exact","outputinitially":true,"state_type":"str","haltifstate":"","halt_if_type":"str","halt_if_compare":"is","outputs":1,"output_only_on_state_change":true,"for":0,"forType":"num","forUnits":"minutes","ignorePrevStateNull":false,"ignorePrevStateUnknown":false,"ignorePrevStateUnavailable":false,"ignoreCurrentStateUnknown":false,"ignoreCurrentStateUnavailable":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"}],"x":110,"y":160,"wires":[["5d73a7027b70b476","5d73a7027b70b476","5d73a7027b70b476"]]},{"id":"48b28d70ea3fa86c","type":"api-call-service","z":"dcb46f81965b861b","d":true,"name":"Trigger","server":"8093ca4.46eb138","version":3,"debugenabled":false,"service_domain":"switch","service":"turn_on","entityId":"switch.gate_opener_trigger","data":"","dataType":"jsonata","mergecontext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","x":600,"y":160,"wires":[[]]},{"id":"5d73a7027b70b476","type":"function","z":"dcb46f81965b861b","name":"","func":"switch (msg.payload) {\n  case 'on':\n    msg.enable = false;\n    msg.icon = \"mdi:gate\";\n    break;\n  case 'off':\n    msg.enable = true;\n    msg.icon = \"mdi:gate-open\";\n    break;\n  default:\n    node.warn(\"Unrecognized Payload: = \" + msg.payload);\n}\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[],"x":260,"y":160,"wires":[["6d82955b97bc34e1","6d82955b97bc34e1","367db4c96c25269f","367db4c96c25269f","6d82955b97bc34e1","367db4c96c25269f"]]},{"id":"3a32283ac06656ab","type":"inject","z":"dcb46f81965b861b","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"on","payloadType":"str","x":110,"y":240,"wires":[["5d73a7027b70b476","5d73a7027b70b476","5d73a7027b70b476"]]},{"id":"3e574c598b685ca8","type":"inject","z":"dcb46f81965b861b","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"off","payloadType":"str","x":110,"y":280,"wires":[["5d73a7027b70b476","5d73a7027b70b476","5d73a7027b70b476"]]},{"id":"367db4c96c25269f","type":"ha-api","z":"dcb46f81965b861b","name":"Set Icon","server":"8093ca4.46eb138","version":1,"debugenabled":true,"protocol":"websocket","method":"get","path":"","data":"{\t   \"type\": \"nodered/discovery\",\t   \"server_id\": \"8093ca4.46eb138\",\t   \"node_id\": \"6d82955b97bc34e1\",\t   \"component\": 'switch',\t   \"config\": {\t       \"name\": \"Gate Control\",\t       \"icon\": icon\t    }\t}","dataType":"jsonata","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":440,"y":220,"wires":[[]]},{"id":"405ea8184aa08c9f","type":"api-current-state","z":"dcb46f81965b861b","d":true,"name":"Status","server":"8093ca4.46eb138","version":3,"outputs":1,"halt_if":"","halt_if_type":"str","halt_if_compare":"is","entity_id":"binary_sensor.gate_opener_contact","state_type":"str","blockInputOverrides":false,"outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"entityState"}],"for":0,"forType":"num","forUnits":"minutes","override_topic":false,"state_location":"payload","override_payload":"msg","entity_location":"data","override_data":"msg","x":590,"y":200,"wires":[["5d73a7027b70b476","5d73a7027b70b476","5d73a7027b70b476"]]},{"id":"8093ca4.46eb138","type":"server","name":"Home Assistant","version":2,"addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":true,"cacheJson":true,"heartbeat":false,"heartbeatInterval":30}]`

**Comment by almirus** [comment]
after send this 
`{
   "type": payload.type,
   "server_id": payload.server_id,
   "node_id": payload.node_id,
   "config": {
       "icon": icon
    },
    "state": payload.state
}`
get error msg : string[101] "API Error. Error Message: extra keys not allowed @ data['config']. Got {'icon': 'mdi:weather-cloudy'}"

**Comment by zachowj** [comment]
@almirus Use the [update config](https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/update-config.html) node to dynamically update entity config values.
