### ISSUE TITLE
Exposed Entities Rename After Each NodeRED Reboot

### ISSUE THREAD

**Issue by sbach89** [zachowj/hass-node-red#126]
Home Assistant 2022.2.9
NodeRED 11.0.4
NodeRED Companion 1.0.6

Everytime NodeRED restarts, for whatever reason, be it an update, or host reboot, exposed entities get duplicated with a _2 at the end, and the original entity is no longer available. Example, I have a switch called 'switch.scene_bedtime'. HA shows this as 'switch.scene_bedtime'. When NodeRED reboots, HA will create a new entity called 'switch.scene_bedtime_2'. If I restart the host, NodeRED, or reload NodeRED Companion, it sometimes corrects and the original entity is available and the new '_2' entity is no longer available.

Any clue what's going on here? Thanks!

**Comment by sbach89** [comment]
`Platform nodered does not generate unique IDs. ID nodered-2251a7d6.97aa98-41c3ad14ff4b0574 already exists - ignoring switch.scene_bedtime_2`

**Comment by sbach89** [comment]
No it is not

**Comment by zachowj** [comment]
Try

1. unload the companion integration
2. reboot HA
3. remove all the entities that are associated with the exposed node
4. reboot HA
5. add back the integration
6. check to see if a entity was created with the correct id minus the `_2`
7. restart NR 
8. check if it created a new entity in HA or used the correct one

**Comment by sbach89** [comment]
That seems to have taken care of it, thank you.

**Comment by Lolcraftspace** [comment]
Did somebody find a solution that works better than the suggestet solution?
Every f*** time I try to change something all my f*** Entities are f** up!!!
