### ISSUE TITLE
Entity node in sub-flow create new entity each time main flow is changed

### ISSUE THREAD

**Issue by snp88** [zachowj/hass-node-red#130]
## Version of the custom_component
v.1.0.7

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
If we add entity node to sub-flow each change in main flow will couse creation of the new sensor entity

Steps to reproduce:
1 create sub-flow
2 create entity via entity node in sub flow
3 add sub-flow to main flow 
![image](https://user-images.githubusercontent.com/46537540/163153145-43db32d7-b5b4-42b2-a674-1df26141e733.png)
4 deploy flows - this will create entity in HA entity name for example _sensor.exapleentityfromnodered_
5 change  and deploy main flow for example - this will create second entity in ha with the name _sensor.exapleentityfromnodered_1_
![image](https://user-images.githubusercontent.com/46537540/163153600-eaa1d80a-7401-49d5-b674-f54ef51825ce.png)
## Debug log

```text

Add your logs here.

```

**Comment by zachowj** [comment]
It's a limitation of the entity node.

https://zachowj.github.io/node-red-contrib-home-assistant-websocket/node/entity.html#configuration

**Comment by snp88** [comment]
thx for clarification :)
