### ISSUE TITLE
node red companion installed but still getting errors and no entities in HA

### ISSUE THREAD

**Issue by denveronly** [zachowj/hass-node-red#133]
Hi all,
I was using this automation for a long time, recently all broke down with no reason, just one morning my curtains didnt open
So i googled and made these steps.
Rebooted
Rebooted the Box,
Reinstalled Companion from hacks with several reboots,
Rreinstalled Companion Manually

When i add in Integrations Tab i get 0 entities just an Integration. (when it was installed but not working i got 28 entities with red sign that are not available, i deleted integration and now i have none)

HA is the latest version, i guess it is some cause with NR auto update that happened during that night it is latest version also

Node red keeps telling me that **This node requires [Node-RED custom integration ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.** in the Node options, but Companion is installed.
What can cause this bug?

**Comment by denveronly** [comment]
Ive managed to fix the issue, for anyone having error
Error: unexpected error (502) error
or Node not deployed.

Be sure to fix any depricated nodes that happen in new NR versions (like for mine stoptimer was deleted and gave errors to whole NR not letting it deploy all of the flows)
when i deleted it all got fixed.

**Comment by neozizen** [comment]
@DenverOnly TY!  Your suggestion fixed it for me.  With the latest release of Node-Red a GeoFence node was deprecated preventing my Node-RED custom integration from working.
