### ISSUE TITLE
Problem with removing entities with home assistant 

### ISSUE THREAD

**Issue by andreassolberg** [zachowj/hass-node-red#135]
I have created a lot of custom sensor entities.

After the latest home assistant update, when I remove one of these entities, and click deploy in node-red, I get:
Deploy failed: 502: Bad Gateway

And I am not able to access node-red unless I restart it.
The node is actually removed from home assistant. So the only problem is that node-red crashes.

The version of HA I am running is:

Home Assistant 2022.7.2
Supervisor 2022.07.0
Operating System 8.2
Grensesnitt 20220707.0 – latest

I'm using Node-red-companion v1.0.9 installed via HACS.

**Comment by MrRudeDog** [comment]
I just installed Node Red (latest build) yesterday to the latest HA build and am experiencing the same issues as the OP. I restarted Node Red dozens of time yesterday whenever I deleted a node.

**Comment by MrRudeDog** [comment]
Thanks for your prompt reply. Today I haven't had any issues. Sorry to post prematurely. 

Sent from the all new AOL app for Android 
 
  On Mon, Jul 11, 2022 at 4:07 PM, ***@***.***> wrote:   


I am able to delete an entity node and NR continues to run. What do NR logs show?
