### ISSUE TITLE
What is the difference between the HA UI Integration and the HACS Integration ?

### ISSUE THREAD

**Issue by oywino** [zachowj/hass-node-red#136]
I ended up installing both, and it seems to work, but I'm not sure I understand what I'm doing.
Since there are (at least) two distinct Integrations; One in HACS and the other is found in the HA UI (or is that one just a result of the first?).  Are they different or just a dependencies? 

I'm just curious...  Should only one of them be installed, or both ?

**Comment by zachowj** [comment]
I'm assuming the "HA UI Integration" you are referring to is the [Node-RED addon](https://github.com/hassio-addons/addon-node-red).

There is a difference between an add-on and an integration. [Add-ons](https://www.home-assistant.io/addons/) are applications that can be installed if you're running a version of Home Assistant with supervisor. [Integration](https://www.home-assistant.io/integrations/) is the part that allows Home Assistant to communicate with an add-on or an external service.

**Comment by zachowj** [comment]
> What I meant by "HA UI" is selecting: _Settings --> Devices & Services --> Integrations --> + Add Integration_

If you manually install or use HACS this is still a required step.

Since this is a custom integration, not included in HA core, you have to install it either manually or using other means. One of the other means is HACS. Which will install it and then also notify you when there's an update. HACS itself is just another custom integration for managing other custom integrations.

**Comment by oywino** [comment]
I see - thanks. I found the docs somewhat scarce (most chapters is only a 404), so I wrote my own (attached).
This is of course specific for my installation (allcontainer based) on my QNAP NAS servers.
[How to integrate NodeRED with Home Assistant.pdf](https://github.com/zachowj/hass-node-red/files/9097120/How.to.integrate.NodeRED.with.Home.Assistant.pdf)

**Comment by zachowj** [comment]
Which docs are you referring to with 404s? The docs for this repo are basically just the README and the docs for HA nodes are https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/

**Comment by oywino** [comment]
I'm sorry - I didn't mean to be rude. This is the only one I found (following the link in the Integration):
https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/custom_integration/#installation

**Comment by zachowj** [comment]
I didn't think you were being rude. I just wanted to be able to fix any errors in the documentation. Thank you
