### ISSUE TITLE
Add entities to device via NodeRed

### ISSUE THREAD

**Issue by peteh** [zachowj/hass-node-red#139]
**Is your feature request related to a problem? Please describe.**

When adding new entities to Homeassistant using NodeRed nodes, it would be cool to add them to a specific devices. E.g. I added a bunch of switches for each room and depending if the switch is on or off, the cleaning robot will clean this particular room when doing the next cleaning run. 

Each of the switches exists as a separate entity and when assigning them to a specific area, they all have to be manually set to said area. If they would be assigned to a specific device, only the device would need to be added to the area. Also there would be a more logical view of which entities belong to a certain function/device. 

**Describe the solution you'd like**

Like entities it should be possible to add devices. Then within the entity node the assigned device could be selected. 

In HA all these assigned entities would show up on the device page of this particular device. 

**Describe alternatives you've considered**
There is no particular alternative I think. I need to assign the area to each entity separately and they show up as single items. 

**Additional context**

PS: thanks for providing this integration. I'm automating a lot of my functionalities using NodeRed and this integration.

**Comment by nunomcruz** [comment]
I would also love to see this!

**Comment by peteh** [comment]
I'm still interested in this feature

**Comment by zachowj** [comment]
https://github.com/zachowj/node-red-contrib-home-assistant-websocket/commit/6c6421298acd176a9632d01ec34356417e163fda

**Comment by peteh** [comment]
So cool, thank you so much! I'll try it as soon as it's available in a release.
