### ISSUE TITLE
I/O in event loop

### ISSUE THREAD

**Issue by balloob** [zachowj/hass-node-red#14]
## Version of the custom_component

Current `master` branch.

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
I was interested in what this integration did. README wasn't very descriptive so browsing through the code and it's doing I/O inside the event loop. This should be done inside the executor worker thread.

https://github.com/zachowj/hass-node-red/blob/256bdda0b7448c3f499804366aea570a8607a31b/custom_components/nodered/__init__.py#L97

Change `async def` -> `def` and then run `result = await hass.async_add_executor_job(check_files)

## Debug log

```text

Add your logs here.

```

**Comment by zachowj** [comment]
Thank you.
