### ISSUE TITLE
Button and Entity node in the same location

### ISSUE THREAD

**Issue by ITensEI** [zachowj/hass-node-red#142]
**Is your feature request related to a problem? Please describe.**
Currently the custom Entity node is under Home Assistant and the Button node was added under a separate Home Assistant Entities section in NR.

**Describe the solution you'd like**
Place them together under one section. Either the top HA or the HA Entities

**Additional context**
A QOL more than anything. I think it makes sense to keep the custom components together.

**Comment by zachowj** [comment]
The entity node is in the process of being broken out into separate nodes, binary sensor, sensor, and switch. These will also be placed under the Home Assistant Entities group along with any new entity-type nodes.
