### ISSUE TITLE
Node-Red not in Menue

### ISSUE THREAD

**Issue by silvermd** [zachowj/hass-node-red#143]
Hello,

I have added Node-RED companion with HACS integration. Then downloaded the Node-RED Companion via Settings Integration.
I can't install or configure anything, only reload, deactivate or delete.

Now NR is not displayed in the left HA menu.

I installed Home Assistant via Proxmox LXC (IP: x.y.z.65), just such a Proxmox Node-RED LXC (IP: x.y.z.100) (node-red-contrib-home-assistant-websocket is installed)

Thanks very much

**Comment by mccasian** [comment]
same here. It seems to be the new version of Home Assistant which does not have the same menu and buttons like in the old tutorials we find on internet

**Comment by Susejer** [comment]
Same me. Version Home Assistant 2022.8.3

**Comment by zachowj** [comment]
This custom component doesn't add Node-RED to the sidebar. That's only available if you're running NR add-on via supervisor.

<https://github.com/hassio-addons/addon-node-red>
