### ISSUE TITLE
Invalid warning message that custom integration needs to be installed

### ISSUE THREAD

**Issue by declanshanaghy** [zachowj/hass-node-red#15]
## Version of the custom_component: 
v0.4.1

## Describe the bug
I have some binary_sensors in my flows that generate the following warning message upon every deploy.
```
Node-RED custom integration needs to be installed in Home Assistant for this node to function correctly.
```
They all work fine, but this warning clutters the debug window.

[See screenshot](https://photos.app.goo.gl/9Eqibds5qUqSvTwt7)
Within the screenshot 2 sensor nodes are visible. The warning is printed by one of them but not the other. There is also a warning from another sensor node that is off screen.

**Comment by declanshanaghy** [comment]
For some reason this warning has now stopped appearing for the sensors shown in that screenshot. However, it is now appearing for a new sensor I just added. It also appears to be preventing that sensor from setting it's state correctly.

**Comment by steveneon** [comment]
i have this issue as well same as above.

**Comment by markozekic** [comment]
Me too :-).

**Comment by zachowj** [comment]
@declanshanaghy @steveneon @markozekic What do you have your deploy method set to?

![image](https://user-images.githubusercontent.com/37859597/77641002-8df89c00-6f18-11ea-8a0f-d8ff8af92ed9.png)

If the server config node has to reestablish connection every time you deploy this can cause the issue. Full will always restart the connection and Modified Flows will sometime restart the connection.

**Comment by declanshanaghy** [comment]
I had it set to Full. The issue isn't happening at the moment.
I changed to Modified Nodes and will keep an eye out for it.

Thx

**Comment by cjramseyer** [comment]
I have this installed on two different instances v0.4.1.
One instance is showing the same error, though it has already been added through integrations.
The other instance does not show this message.  BOth instances of HA have been restarted

**Comment by Jpsy** [comment]
I had dozens of these msgs on every deploy. Setting the deploy method to "Modified Nodes" solved the problem at hand. But shouldn't this warning be issued only if no connection could be established.

**Comment by zachowj** [comment]
@Jpsy When you do a Full Deploy it also reinitializes the configuration node which is the node that controls the connection to HA. When the HA nodes all reinitialize, the connection to HA could be in several different states. If it hasn't connected and read the HA config to check if the custom component has been installed you will get the error.

**Comment by Jpsy** [comment]
@zachowj so this is basically a kind of race condition. Is there something I can do to change my config node so that the HA connection is reliably started first?

**Comment by gitolicious** [comment]
For me the message was shown when I added the HA component but ignored the last step:

> In the HA UI go to "Configuration" -> "Integrations" click "+" and search for "Node-RED"

Just in case someone else stumbles upon the same...
