### ISSUE TITLE
Integration stopped working

### ISSUE THREAD

**Issue by marcgarciamarti** [zachowj/hass-node-red#16]
## Version of the custom_component
v0.4.1

## Describe the bug
Randomly the integration between Node-red and home assistant will die and all the nodes appear as disconnected. 
![image](https://user-images.githubusercontent.com/12695572/76027991-eba95200-5f31-11ea-9192-87c03cdcf242.png)

## Debug log

```
5 Mar 12:01:41 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:01:46 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:01:52 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:01:57 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:02 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:07 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:12 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:17 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:22 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:28 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core
5 Mar 12:02:33 - [info] [server:Home Assistant] WebSocket Connecting http://supervisor/core

```

**Comment by zachowj** [comment]
This isn't an integration issue.

Take a look here https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/212 and https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/209#issuecomment-592392331

**Comment by marcgarciamarti** [comment]
Thank you @zachowj ! I actually downgraded to 105.x yesterday because I could not find a way to fix it. Many thanks. You seem to have hit the nail right on its head
