### ISSUE TITLE
Update problem with device node

### ISSUE THREAD

**Issue by Leopoll** [zachowj/hass-node-red#160]
After upgrading from version 1.0.9 to 1.1.2 and Node-RED to 14.0.1, all HA nodes give an error. I restored the backup, but now the "device" nodes do not work (it does not give an error, it just does not work), the rest of the HA nodes work fine. rebooted many times - but nothing helps. Home Assistant 2022.12.8.
![image](https://user-images.githubusercontent.com/33684678/210289227-148b750c-756e-4b4f-8062-560c0d142c2f.png)
![image](https://user-images.githubusercontent.com/33684678/210289312-4c575e53-a98c-453b-b8da-37f5f1f66d92.png)

**Comment by zachowj** [comment]
what's the status under the device node now? Is there anything in the logs?

**Comment by Leopoll** [comment]
Status: running
Now I'm trying to update again. Again Error: Server config node not found on all nodes.

**Comment by Leopoll** [comment]
```
[03:43:29] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js "--settings" "/etc/node-red/config.js"
3 Jan 03:43:36 - [info] 
Welcome to Node-RED
===================
3 Jan 03:43:36 - [info] Node-RED version: v2.2.2
3 Jan 03:43:36 - [info] Node.js  version: v16.14.0
3 Jan 03:43:36 - [info] Linux 5.15.76-v7+ arm LE
3 Jan 03:43:39 - [info] Loading palette nodes
3 Jan 03:43:51 - [info] Dashboard version 3.1.6 started at /endpoint/ui
3 Jan 03:43:54 - [info] Settings file  : /etc/node-red/config.js
3 Jan 03:43:54 - [info] Context store  : 'default' [module=memory]
3 Jan 03:43:54 - [info] User directory : /config/node-red/
3 Jan 03:43:54 - [warn] Projects disabled : editorTheme.projects.enabled=false
3 Jan 03:43:54 - [info] Flows file     : /config/node-red/flows.json
3 Jan 03:43:55 - [info] Server now running at http://127.0.0.1:46836/
[03:43:55] INFO: Starting NGinx...
3 Jan 03:43:55 - [info] Starting flows
3 Jan 03:43:58 - [info] Started flows
3 Jan 03:43:58 - [info] [server:9055ffae.cacf6] Connecting to http://supervisor/core
3 Jan 03:43:59 - [error] [api-call-service:Fun off] Call-Service attempted without connection to server.
3 Jan 03:43:59 - [error] [api-current-state:если подсветка вкл] Entity could not be found in cache for entity_id: switch.0x00124b0019360934_l1
3 Jan 03:43:59 - [info] [server:9055ffae.cacf6] Connected to http://supervisor/core
3 Jan 03:45:32 - [info] Stopping modified flows
3 Jan 03:45:32 - [info] Stopped modified flows
3 Jan 03:45:32 - [info] Starting modified flows
3 Jan 03:45:32 - [info] Started modified flows
```

![image](https://user-images.githubusercontent.com/33684678/210290655-3d6803b6-60de-485d-8b4e-70ca49656fb5.png)

**Comment by zachowj** [comment]
Node-RED is not seeing that the NR companion custom component is setup in HA. If it was the status of the device nodes would say `registered`.

**Comment by Leopoll** [comment]
What to do? I didn't change anything.
Some HA nodes are working now.
![image](https://user-images.githubusercontent.com/33684678/210291171-f9832915-95b3-42fc-8f2f-b24c6dc71642.png)

**Comment by zachowj** [comment]
Most of the "Standard" nodes don't require the custom component. Check HA and make sure the custom component is still added. 

In the Home Assistant UI go to "Configuration" -> "Integrations"  and look for Node-RED.

If not, add it.

Step 5

<https://github.com/zachowj/hass-node-red#hacs>

**Comment by Leopoll** [comment]
Yes, it was missing. Thanks a lot.
But what about 1.1.2 version? Why I can't update?

**Comment by zachowj** [comment]
Pretty sure it had nothing to do with version 1.1.2 but the add-on update. After you update make sure the "I use the add-on" is checked in the HA server config in NR.

**Comment by Leopoll** [comment]
Yes, it's not the version 1.1.2.
Now updated only NR on 14.01. All nodes HA with errors.
![image](https://user-images.githubusercontent.com/33684678/210358405-9d17b606-1743-4d40-a009-4df8e51188e6.png)
![image](https://user-images.githubusercontent.com/33684678/210358494-d4895d7c-b8bd-4bb4-a1e2-00127e505f0d.png)

**Comment by zachowj** [comment]
There should be an error in the debug window. What does it say?

**Comment by Leopoll** [comment]
Now it's empty. Last time was the "Error: Server config node not found"

**Comment by zachowj** [comment]
under the deploy button run "Restart all flows" and it should produce the error

**Comment by Leopoll** [comment]
Error: Invalid server config
Error: Server config node not found

**Comment by zachowj** [comment]
If you open the nodes with error and select a server does the error go away?

**Comment by Leopoll** [comment]
No. Error doesn't go away

![image](https://user-images.githubusercontent.com/33684678/210361791-e0c252f2-01b9-48f8-8db9-d6e9de4340d1.png)

**Comment by Leopoll** [comment]
And the device node can't find any device.
![image](https://user-images.githubusercontent.com/33684678/210362366-09b90bd5-310b-4374-8407-9062cf9cef10.png)

**Comment by zachowj** [comment]
The device node won't find any devices until it has a connection to HA

**Comment by Leopoll** [comment]
No, only one.

**Comment by zachowj** [comment]
Can you export your server config node and post it here?

**Comment by Leopoll** [comment]
`[
    {
        "id": "9055ffae.cacf6",
        "type": "server",
        "name": "",
        "version": 5,
        "addon": true,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "",
        "connectionDelay": false,
        "cacheJson": false,
        "heartbeat": false,
        "heartbeatInterval": "",
        "statusSeparator": "",
        "enableGlobalContextStore": true,
        "credentials": {}
    }
]`

**Comment by zachowj** [comment]
Out of ideas at the moment. You could try creating a new server config and using that with an events state node and see if it connects.

**Comment by Leopoll** [comment]
Creating a new server was not helpfull. Now NR 11.1.1, NR Companion 1.1.2. All is working. Problem with NR 14.

**Comment by avataru** [comment]
No need to open another issue since it looks like I'm in a similar situation. I have HA 2022.12.8, NR 3.0.2, node-red-contrib-home-assistant-websocket 0.48.0 and NR Companion 1.1.2.

With "Using the Home Assistant Add-on" checked I get the following errors:
* "Error: Supervisor token not found." on the configuration node
* "Error: Server config node not found" on each HA node in my flows

`{"id":"c22a2efd1032de6a","type":"server","name":"Home Assistant","version":5,"addon":true,"rejectUnauthorizedCerts":false,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":": ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"default","statusTimeFormat":"h:m","enableGlobalContextStore":false}`

If I untick it and add set the base URL and access token it won't show any errors but won't see any entities on the `get entities` so this option won't work either.

`{"id":"c22a2efd1032de6a","type":"server","name":"Home Assistant","version":5,"addon":false,"rejectUnauthorizedCerts":false,"ha_boolean":"y|yes|true|on|home|open","connectionDelay":false,"cacheJson":true,"heartbeat":false,"heartbeatInterval":"30","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":": ","statusYear":"hidden","statusMonth":"short","statusDay":"numeric","statusHourCycle":"default","statusTimeFormat":"h:m","enableGlobalContextStore":false}`

**Comment by Leopoll** [comment]
I'm sorry. Something strange is happening.
After rebooting the server (not only the HA, but the entire physical device), node-red-contrib-home-assistant-websocket disappears from the NR palette. Why?

**Comment by rlust** [comment]
I am having same issue. The devices I created in NR work some times then they are unavailable. Last issue was devices are there but no entities.
