### ISSUE TITLE
trying to install node-red for the fist time, can't start it

### ISSUE THREAD

**Issue by blightniak** [zachowj/hass-node-red#163]
I'm new to Home Assistant and Node-Red.  I have installed Node-Red add-on but can't get it start

I'm running
- Ubuntu Home Assistant 2022.12.7 Frontend 20221213.1 - latest-
- Also tried on Debian Home Assistant 2023.1.1, Supervisor 2023.01.dev0602, Frontend 20230104.0 - latest

I did the following steps

- HACS -> Integration -> + explore & download repositories
- Select node-red companion
- download
- V1.1.2
- download
- Back
- In HACS integration node-red companion is red with pending restart
- Restart Home assistant
- In HACS integration node-red companion is not red now
- Settings -> Devices & Services -> Integrations
- Select + add integration
- Search for node and select node-red companion
- Do you want to add Node-RED Companion to Home Assistant? Select submit
- Success! Created configuration for name -> select Finish.
- Restart browser
- Nothing in home-assistant.log just
    - 2023-01-08 18:54:05.804 WARNING (SyncWorker_3) [homeassistant.loader] We found a custom integration nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
- No node red on left
- Where do you configure it?

I have remove and restarted a number of times, have installed 

please help I'm sure this is just a user problem

thanks

**Comment by zachowj** [comment]
What you installed via HACS is an integration. There's a difference between add-ons and integrations. So that you know, you still need to install the add-on. The Node-RED custom integration allows you to do additional things in Home Assistant using NR.

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md>

**Comment by Ewoodster** [comment]
Hello, 

I also have a problem installing node-red companion.

Node red is running successfully, but I can't download node-red companion. When I try to download via HACS, the blue circle will keep spinning forever without actually downloading anything.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/100773537/211484336-0803d874-3e1f-4faa-8843-b431c6ab4d7e.png">

When I try it the manual way (download files to PC, copy them to HA->config/custom_components/node_red via samba), it will not show up in the integrations, even after restart and refresh in the broswer.

Maybe I am missing something, but I've tried for 1 1/2 days without success. 

Could you please check if I did something wrong?

**Comment by zachowj** [comment]
@Ewoodster Using HACS just worked for me. Might check your HA logs for an error. When you try to manually install it are you only copying over the files in the custom_component/nodered directory of the repo and not the whole repo?

**Comment by Ewoodster** [comment]
Thanks for your super quick reply. I downloaded the code via Zip file, hoping it contains all the necessary data.

I figured I made a mistakte by naming the folder in custom_components "node-red" instead of "nodered", but this didn't fix the problem.

**Comment by Ewoodster** [comment]
Nevermind, I got it to work. When I unzipped the file, it created new folders /custom_components/nodered inside the nodered folder which I manually created. When I copied the files from the subfolders into the main folder, restarted and refreshed the broswer, it finally showed up in the integrations.

Thanks, works like charm now.

**Comment by angelmartinez93** [comment]
Hello. Taking advantage of this thread. I am also having trouble integrating node red with HA. When creating a room in Node-RED and adding the HA server, I get the following error:

"Attention: This node requires Node-RED custom integration version 1.1.0+ to be installed in Home Assistant for it to function."

Can you help me about this error?

**Comment by ronyn77** [comment]
Hello,

I have two home assistant installation and I tried to add the nodered companion to the existing node red integration. In both cases in the log file I found the warning message :"WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant".
Looking at both integration tabs, I can see : 
![image](https://user-images.githubusercontent.com/22024600/212632610-cc988eea-d96c-4a7a-be1d-1c5e91ef9f49.png)

I am not sure, but on the net I found pictures of this integration which shows some entities under the name. Here it is empty. How can I check if it works or not? Or what should I try to do to make it work?

**Comment by ronyn77** [comment]
> > 
> 
> Hey, having this same issue. Any advice?

The entity was empty, because you need to create such a entity. The warning in the logs is not important, so you bypass it.
To create the entity, inside nodered you have to choose one of the new available nodes and configure it. After that, it works.
