### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by StoricU** [zachowj/hass-node-red#166]
Hi,

Have not been working with node-red for a few months, but the other day when I was gonna change something in a flow I discovered that I'm not able to deploy.

When I press Deploy, it just turns gray and keeps "spinning"
![image](https://user-images.githubusercontent.com/50556267/214279812-02584a08-e289-40bc-8836-cdc9dd29e123.png)

How/where can I find logs or information to investigate what is happening?
Or is there someone that know what I can do to solve this issue?

**Comment by zachowj** [comment]
This would be an issue with Node-RED. Try their discourse for help.
