### ISSUE TITLE
Additional Entity Node Types

### ISSUE THREAD

**Issue by Glazzanz** [zachowj/hass-node-red#17]
Would it be possible to expand on the Entity Node Types from the current Switch, Sensor and Binary Sensor to also include the other supported entity types?

For example, I would use Light, Climate and Alarm Control Panel.

Sorry, if this is on a roadmap somewhere.

Cheers
David

**Comment by zachowj** [comment]
At this time I don't have any plans on adding more types of entity nodes. If someone wants to do a pull request for it that would be acceptable. 

Also, I believe you could easily build the three mention integrations with what's available in NR and using the template integrations for each type.
