### ISSUE TITLE
Set entity_picture on sensor

### ISSUE THREAD

**Issue by hmorkemo** [zachowj/hass-node-red#171]
It would be very nice if it was possible to set an entity's (sensor, binary_sensor etc) entity_picture in Node RED.
Since the entity_picture can bed used when displaying a sensor in lovelace/mushroom cards.

**Comment by hmorkemo** [comment]
Nice! But how can I set the entity_picture when setting the sensor's value from node red? I need to change the picture depending on some calculations or the state

**Comment by zachowj** [comment]
The update config node is used to update the entity config option dynamically.
