### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by 4Fire4** [zachowj/hass-node-red#173]
I'm new to home assistant and node-red, and I'm probably stupid, but I spent over two hours to install this. I think the reason is that the installation instructions are incomplete. I did not understand you should press the blue button because the text did not say it. Can you please update the text to explicitly tell "push this button"?

Whould also be helpful if you add some explanation about what that blue button actually does.

![image](https://user-images.githubusercontent.com/26690347/226146349-35595f8a-2e77-4892-92fb-110488e776aa.png)

**Comment by zachowj** [comment]
Clicking the button is a shortcut to the same location the directions in step 5 would have taken you.

**Comment by 4Fire4** [comment]
I disagree. The written instructions in bullet point 5 is incomplete.

If you follow the written instructions in bullet point number 5 word by word it tells you to go search for "Node-RED". Searching for "Node-RED" will achieve nothing. It will take you to the Node-RED info page. What to do then? There is vital information missing. 

Here are some possibilities after searching for Node-RED: 
- if Node-RED is not already installed: install Node-RED?
- if Node-RED was already installed: restart it? unistall, then re-install? something else?

In my case I had Node-RED already installed. Searching for Node-RED achieved nothing in my case. Clicking the button activated some process that integrated Node-RED with hass-node-red and everything works now.
