### ISSUE TITLE
can't do the integration

### ISSUE THREAD

**Issue by pedrotainha** [zachowj/hass-node-red#18]
When searching for this integration, appears an empty line:
![image](https://user-images.githubusercontent.com/4137458/76704872-f69f7780-66d3-11ea-93f2-0730f1eef05c.png)

I've put the contents in the folder as described in the instructions:
![image](https://user-images.githubusercontent.com/4137458/76704910-264e7f80-66d4-11ea-803a-0039db095e50.png)

when i select it showed loading icon during some time, but then only this:

![image](https://user-images.githubusercontent.com/4137458/76705023-cc9a8500-66d4-11ea-8127-dac9f34dab87.png)

And i don't have the integration in the list as installed.

**this is what appeared me in the logs only:**
`2020-03-15 15:37:14 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

versions:

![image](https://user-images.githubusercontent.com/4137458/76705062-33b83980-66d5-11ea-9382-31d21889be1c.png)

**Comment by zachowj** [comment]
Looks like you're missing the `.translations` directory

**Comment by pedrotainha** [comment]
thanks it was that. and i could continue

**Comment by niccolobusato** [comment]
hi, still not working for me, same problem but i have the .translations directory. does exist a minimum version requirement? i'm on 0.94.4 on this installation..

**Comment by zachowj** [comment]
@niccolobusato Requires 0.96.0 because that's when custom components were able to use the config flow.

**Comment by gdr2404** [comment]
I'm not getting Node Red in the UI configurations either. 

Running HA 0.110.2
Installed via Hacs
translations shows in my custom_components/nodered.

Any advice would be much appreciated.

**Comment by skarabaraks** [comment]
> I'm not getting Node Red in the UI configurations either.
> 
> Running HA 0.110.2
> Installed via Hacs
> translations shows in my custom_components/nodered.
> 
> Any advice would be much appreciated.

Same here - Installed via HACS, followed the documentation and enabled node red in HA integrations but not sure what happens next?
