### ISSUE TITLE
Deleted entities get stuck in HA

### ISSUE THREAD

**Issue by fredck** [zachowj/hass-node-red#181]
When creating a new button directly in NR and configuring a new entity in HA, the button gets properly created and listed in HA entities. All good here.

If we delete the button from NR and remove the entity configuration, the relative entity in HA gets "unavailable", which is ok, but it is not possible to remove it by entering the entity settings since the "Delete" button is disabled (which is not ok):

![image](https://github.com/zachowj/hass-node-red/assets/630060/9548e3de-ce2c-477c-87c5-57fd1789cc87)

It seems like that (now useless) entity will be there forever.

**Comment by fredck** [comment]
No changes.

**Comment by MaxVonEvil** [comment]
Seeing the same, what worse is after the latest update a week ago, all the switches created in NR companion are ON per default.

**Comment by minermartijn** [comment]
Same here, i cannot delete them from home assistant. But already have them deleted in NodeRed. So now got stuck entities in HA which i really want to remove.

**Comment by XxTopKillerzZ** [comment]
I have the same problem.
Also, If I update entities naming in Node-RED they sometimes do not update or take some resets to do so
