### ISSUE TITLE
Module not found / server, ha-entity-config, ha-sensor

### ISSUE THREAD

**Issue by tommy99999999** [zachowj/hass-node-red#183]
Node Red Version: 14.2.2 

After restarting HA/Node Red on RPI4 i lost all my sensors in HA and get the message in NodeRed that the HA-Sensor modules are not loaded.

I searched the last 3 days for any similar issue to repair it myself, reinstalled Node Red Addon and the HACS Custom Plugin several times, tried to downgrade Node Red, but nothing helps. Thanks for Support.

Add your logs here:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Node-RED
 Flow-based programming for the Internet of Things
-----------------------------------------------------------
 Add-on version: 14.2.2
 You are running the latest version of this add-on.
 System: Home Assistant OS 10.2  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.6.0b4
 Home Assistant Supervisor: 2023.06.0
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-nginx: starting
s6-rc: info: service init-customizations: starting
s6-rc: info: service init-customizations successfully started
s6-rc: info: service init-nodered: starting
s6-rc: info: service init-nginx successfully started
up to date, audited 68 packages in 4s
5 packages are looking for funding
  run `npm fund` for details
2 high severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
Run `npm audit` for details.
s6-rc: info: service init-nodered successfully started
s6-rc: info: service nodered: starting
s6-rc: info: service nodered successfully started
s6-rc: info: service nginx: starting
s6-rc: info: service nginx successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[06:16:33] INFO: Starting Node-RED...
> start
> node $NODE_OPTIONS node_modules/node-red/red.js --settings /etc/node-red/config.js
4 Jun 06:16:38 - [info] 
Welcome to Node-RED
===================
4 Jun 06:16:38 - [info] Node-RED version: v3.0.2
4 Jun 06:16:38 - [info] Node.js  version: v18.16.0
4 Jun 06:16:38 - [info] Linux 6.1.21-v8 arm64 LE
4 Jun 06:16:40 - [info] Loading palette nodes
4 Jun 06:16:47 - [info] Dashboard version 3.5.0 started at /endpoint/ui
4 Jun 06:16:49 - [warn] ------------------------------------------------------
4 Jun 06:16:49 - [warn] [node-red-contrib-home-assistant-websocket/all] SyntaxError: Malformed JSON in file: /config/node-red//node-red-contrib-home-assistant-websocket.json
Unexpected token  in JSON at position 0
4 Jun 06:16:49 - [warn] [node-red-contrib-arc-modbus-puls/arc-modbus-polling] 'arc-modbus-polling' already registered by module node-red-contrib-arc-modbus
4 Jun 06:16:49 - [warn] [node-red-contrib-arc-modbus-revise/arc-modbus-polling-revise] 'arc-modbus-polling' already registered by module node-red-contrib-arc-modbus
4 Jun 06:16:49 - [warn] ------------------------------------------------------
4 Jun 06:16:49 - [info] Settings file  : /etc/node-red/config.js
4 Jun 06:16:49 - [info] Context store  : 'default' [module=memory]
4 Jun 06:16:49 - [info] User directory : /config/node-red/
4 Jun 06:16:49 - [warn] Projects disabled : editorTheme.projects.enabled=false
4 Jun 06:16:49 - [info] Flows file     : /config/node-red/flows.json
4 Jun 06:16:49 - [info] Server now running at http://127.0.0.1:46836/
4 Jun 06:16:49 - [info] Waiting for missing types to be registered:
4 Jun 06:16:49 - [info]  - server
4 Jun 06:16:49 - [info]  - ha-entity-config
4 Jun 06:16:49 - [info]  - ha-sensor
[06:16:49] INFO: Starting NGinx...

**Comment by zachowj** [comment]
Looks like the file, `node-red-contrib-home-assistant-websocket.json`, got corrupted. Delete it and the HA nodes should load.

**Comment by tommy99999999** [comment]
Thanks, that was the problem.
Solved!

**Comment by tommy99999999** [comment]
Solved
