### ISSUE TITLE
Node-Red Integration does not Appear 

### ISSUE THREAD

**Issue by edwar2** [zachowj/hass-node-red#186]
## Version of the custom_component
Home Assistant 2023.6.1
HACS Integration version: | 1.32.1<<------->>Node-Red Companion v1.2.0
Node-Red 3.0.2: Maintenance Release

## Describe the bug

I am running Homeassitant and Node Red as docker containers, In HomeAssistantant UI Integrations only shows Node-Red Companion I installed it but I keep on getting the massage in Node Red UI  "Attention: This node requires [Node-RED custom integration version 1.1.0+ ](https://github.com/zachowj/hass-node-red) to be installed in Home Assistant for it to function.", when I try to add a new sensor. Thanks in Advance

## Debug log

21 Jun 00:41:32 - [error] [ha-binary-sensor:891e8c066077d858] Error: Invalid entity config
21 Jun 00:41:32 - [info] Started flows
21 Jun 01:08:43 - [info] Stopping flows
21 Jun 01:08:43 - [info] Stopped flows
21 Jun 01:08:43 - [info] Updated flows
21 Jun 01:08:43 - [info] Starting flows
21 Jun 01:08:43 - [error] [server:6fbed37fc3b327b7] Error: No credentials provided
Error: Circular config node dependency detected: 18bbefe35fa29ee1
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:172:43)
    at start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/index.js:394:33)
21 Jun 01:08:43 - [error] [ha-sensor:5e794ec631e6540c] Error: Invalid entity config
21 Jun 01:08:43 - [info] Started flows

**Comment by zachowj** [comment]
> 21 Jun 01:08:43 - [error] [server:6fbed37fc3b327b7] Error: No credentials provided

You don't have a valid config, so it can't connect to HA to know if the custom component is installed.

**Comment by edwar2** [comment]
I am sorry for my lack of knowledge, I'm kind of new to node-red, could you tell me how can I provide credentials to homeassistant.

**Comment by zachowj** [comment]
<https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/>

**Comment by edwar2** [comment]
Thanks. I generated a long live token in homeassistant and added to the server config in node red. Problem Solved
