### ISSUE TITLE
Entity customised areas setting is not retained.

### ISSUE THREAD

**Issue by sotatech** [zachowj/hass-node-red#199]
## Version of the custom_component
2.0.0

Home Assistant 2023.7.2
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

I have a Cytech alarm system connect to HA via the Node-RED companion. One device is configured for the zones, so it contains binary sensors for every zone. In HA settings for each entity I turn off the option for the entity to use the device area, and set each one according to their location. If I make a change to the flow and deploy it, the area setting for the entity is reset to the default.
I have used this feature with other integrations, and the setting is retained.
## Debug log

```text

Logs attached.
[home-assistant_nodered_2023-07-17T08-26-38.078Z.log](https://github.com/zachowj/hass-node-red/files/12067417/home-assistant_nodered_2023-07-17T08-26-38.078Z.log)


```

**Comment by sotatech** [comment]
[home-assistant_nodered_2023-07-17T08-26-38.078Z.log](https://github.com/zachowj/hass-node-red/files/12067430/home-assistant_nodered_2023-07-17T08-26-38.078Z.log)

**Comment by zachowj** [comment]
`2023-07-17 09:26:10.884 INFO (MainThread) [custom_components.nodered] Entity removed: switch.comfort_output_001`

At this point in the log, do recall what action is being taken in NR? The entity should only be removed from HA if you didn't the entity config and deployed.

**Comment by zachowj** [comment]
Did you remove the custom component, then re-add it?

**Comment by sotatech** [comment]
I notice that when I do a reload of the integration, I get a lot of errors about the platform not generating unique IDs:

`2023-07-19 10:40:02.585 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform nodered does not generate unique IDs. ID nodered-77e1e680.210de8-041bf28f19b9896a already exists - ignoring binary_sensor.shed_smoke_detector
2023-07-19 10:40:02.586 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform nodered does not generate unique IDs. ID nodered-77e1e680.210de8-041bf28f19b9896a already exists - ignoring binary_sensor.shed_smoke_detector
2023-07-19 10:40:02.587 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform nodered does not generate unique IDs. ID nodered-77e1e680.210de8-041bf28f19b9896a already exists - ignoring binary_sensor.shed_smoke_detector
2023-07-19 10:40:02.587 ERROR (MainThread) [homeassistant.components.binary_sensor] Platform nodered does not generate unique IDs. ID nodered-77e1e680.210de8-4198d5c696950595 already exists - ignoring binary_sensor.utility_room_pir_sensor`

**Comment by sotatech** [comment]
I did some more testing and I found that by clearing the area setting for the device, I could then customise the area for each entity and it would be retained through a reload or restart of HA.
So it would appear that the integration is assuming that all entites associated with a device will have the same area.
