### ISSUE TITLE
CPU high/memory leak with Node Red and Home Assistant 0.108.0

### ISSUE THREAD

**Issue by McGiverGim** [zachowj/hass-node-red#20]
## Version of the custom_component

6.1.4 (I think is the latest version)

## Configuration

I'm not too sure what to add here, the problem is not related with nothing that I can detect.

## Describe the bug

Since the update to Home Assistant 0.108.0 the CPU has gone higher and the memory of the Home Assistant AND Node RED addon grows constantly. I have verified this with a `docker stats` command.

If I stop the Node RED docker, the memory of Home Assistant seems to be stable.

Here is a graph of the memory/CPU usage since installed Home Assistant 0.108.0. I have restarted the system several times:
![image](https://user-images.githubusercontent.com/2673520/78886081-ee7df200-7a5d-11ea-9c74-3565f3cde651.png)

Is not sure 100% that Node Red is the culprit of that, so I open this issue to see if others have installed this new version of Home Assistant to see if they have the same problem and can we locate where the problem is.

## Debug log

I'm not too sure what to add here, maybe a log of the system starting and the first 5 minutes of execution? I have it, but maybe is too big. Must I filter it by something?

**Comment by zachowj** [comment]
This repo is for the custom integration which runs inside HA not NR.

https://github.com/hassio-addons/addon-node-red - this the repo for the HA Node-RED add-on.
achowj/node-red-contrib-home-assistant-websocket - repo for the NR HA nodes but I haven't heard of any other reports of CPU usage increase for the HA nodes.
