### ISSUE TITLE
Webhook Node not loading

### ISSUE THREAD

**Issue by montaque22** [zachowj/hass-node-red#202]
## Version of the custom_component

- The node-red addon is up-to-date.
- The node red companion is also present
- node-red-contrib-home-assistant-websocket is also installed (vers. 0.55.1)

## Configuration
This issue can be easily seen when using a webhook node by itself within node red. No configuration is really needed. But here is an example of my webhook node
```json
[{"id":"8eba25a3552a100b","type":"ha-webhook","z":"6161d870e25ec591","name":"","server":"228d3d53.df8e02","version":2,"outputs":1,"webhookId":"0AEr9YAoDe0tYRYsAnkI0eKmeSDeaf6A","method_get":false,"method_head":false,"method_post":true,"method_put":true,"outputProperties":[{"property":"topic","propertyType":"msg","value":"","valueType":"triggerId"},{"property":"payload","propertyType":"msg","value":"","valueType":"data"}],"payloadLocation":false,"payloadLocationType":false,"headersLocation":false,"headersLocationType":false,"x":100,"y":680,"wires":[["940f290432704f7b"]]},{"id":"228d3d53.df8e02","type":"server","name":"Home Assistant","addon":true}]
```

## Describe the bug

Webhook nodes no longer load or respond to requests within Home assistant node-red. Interestingly, the webhooks trigger within Home Assistant still works. When node red Builds or is restarted a none helpful error message displays (See the debug logs)

## Debug log

```text

[error] [ha-webhook:8eba25a3552a100b] Error registering entity. Error Message: [object Object]

```

**Comment by zachowj** [comment]
I had this issue, but then could reproduce it. If you edit the node, change the name, and then deploy. Does it register the webhook?

**Comment by montaque22** [comment]
Yup tried change the `name`, the `id` and the `allowed methods` but i still got the same error

**Comment by zachowj** [comment]
Are you running the latest version of the custom component?

**Comment by montaque22** [comment]
When you say "custom component" are you refering to the webhook node? How would i find the version of that node? 
> Based on the docs i know there is a dependency on the Node Red Companion integration and a dependency on node-red-contrib-home-assistant-websocket (which is at vers. 0.55.1)

**Comment by zachowj** [comment]
> The node red companion is also present

Node-RED companion is the custom component

**Comment by montaque22** [comment]
Then yes. As far as i am aware it is up to date. What is the best way to double check?

**Comment by montaque22** [comment]
Damn...... No. It wasn't updated. I went to HACS and can see the version numbers. I'll update it and get back to you

**Comment by montaque22** [comment]
Well that's embarrassing 🫣 but im glad its working. Thank you for pointing that out. I appreciate your help!
