### ISSUE TITLE
Node Red Time Not Synced with System

### ISSUE THREAD

**Issue by rodhall** [zachowj/hass-node-red#204]
## Configuration

```yaml
Add your logs here.
```

## Debug log

```text

Add your logs here.

```

**Comment by zachowj** [comment]
This package is a custom component for Home Assistant. I'm assuming you're running Node-RED as a supervisor add-on. 

<https://github.com/hassio-addons/addon-node-red/blob/main/node-red/DOCS.md#time-zone-configuration>
