### ISSUE TITLE
Webhook Error Registering 

### ISSUE THREAD

**Issue by blairlukacs** [zachowj/hass-node-red#210]
## Describe the bug

When I create a Webhook node, name it, and deploy, I receive an immediate error message: 
"Error registering entity. Error Message: [object Object]"
 
Have installed:
 v3.1.0 of Node Red
0.56.1 of node-red-contrib-home-assistant-websocket
v2.2.0 Node-RED Companion - added as integration 
<img width="682" alt="nodewebhook" src="https://github.com/zachowj/hass-node-red/assets/73766687/3a40c31b-e976-4ce5-9bbe-f2ee65d43b77">

**Comment by JvdMaat** [comment]
Is this related to 3.0.0 requiring websocket 0.57 (https://github.com/zachowj/node-red-contrib-home-assistant-websocket) on the Nodered side, but 0.57 hasn't been released? So people should not update to 3.0.0?

**Comment by blairlukacs** [comment]
I would just note that the issue existed for me prior to updating to 3.0.0.  As of typing this I have updated and the issue is ongoing. Will monitor the 0.57 release when it occurs and check back.

**Comment by zachowj** [comment]
0.57 will at least give you a better error message. What is the config of the webhook node?

**Comment by blairlukacs** [comment]
The configuration is very basic- Just brought the node in, left the default ID, named it and attached a debug. Not passing anything through except the default output properties of topic and payload. Home Assistant Server is the same as with my other nodes and flows. - Appreciate the help

**Comment by JvdMaat** [comment]
> 0.57 will at least give you a better error message.

What is the ETA on 0.57?

**Comment by blairlukacs** [comment]
I have update to 0.57.0 The alert now reads: " Error registering entity. Error Message: "extra keys not allowed @ data['allowed_methods']. Got ['POST', 'PUT']" "

**Comment by zachowj** [comment]
What version of Home Assistant are yoy running?

**Comment by blairlukacs** [comment]
2023.9.2

**Comment by zachowj** [comment]
Run this flow in Node-RED. What version does it show in the debug window?

```
[{"id":"9960738fe719028b","type":"ha-api","z":"120358abd7c22d30","name":"","server":"","version":1,"debugenabled":false,"protocol":"websocket","method":"get","path":"","data":"{\"type\": \"nodered/version\"}","dataType":"jsonata","responseType":"json","outputProperties":[{"property":"payload","propertyType":"msg","value":"","valueType":"results"}],"x":334,"y":4960,"wires":[["f128c0776b475a41"]]},{"id":"c4fc45de14e386c8","type":"inject","z":"120358abd7c22d30","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":196,"y":4960,"wires":[["9960738fe719028b"]]},{"id":"f128c0776b475a41","type":"debug","z":"120358abd7c22d30","name":"debug 135","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":490,"y":4960,"wires":[]}]
```

**Comment by blairlukacs** [comment]
When I bring it in an deploy I get an error:

<img width="371" alt="image" src="https://github.com/zachowj/hass-node-red/assets/73766687/33ab0eff-3de3-46f4-a69c-ec4829f93b31">

The debug is as follows:
<img width="674" alt="image" src="https://github.com/zachowj/hass-node-red/assets/73766687/aaa8a1b0-aa9c-4a09-a55a-7e10be6f46d2">

**Comment by blairlukacs** [comment]
Update: went in and added a name to the API node. It deployed with this : 0.4.5

**Comment by zachowj** [comment]
That's the version of this component you have installed in Home Assistant. So you don't have version 2.2.0 installed.

**Comment by blairlukacs** [comment]
Very strange, when I check in HACS it looks like I am updated.
I tried to delete the integration and re-add manually, hoping this would resolve it. 
Steps I took in order (apologies trying to be complete):
-Deleted the Integration on the Integration page
-Deleted the Integration in HACS
-Restarted HA Server
-Deleted the Nodered folder in Custom Components
-Restarted HA Server
-Restarted Node Red Add On
**If I go to integration page at this point and go to add an integration Node Red appears in the list still. I didn't add it yet.
<img width="391" alt="image" src="https://github.com/zachowj/hass-node-red/assets/73766687/0b0a0863-f84e-4967-b697-84a68dcbb208">
-Downloaded the v3.0.1 repository 
-Manually added the nodered folder into Custom Components
-Restarted HA Server
-Selected integrations, refreshed browser, clicked add integration, selected node red. Got this blank submit pop up:
<img width="343" alt="image" src="https://github.com/zachowj/hass-node-red/assets/73766687/0f993586-0318-417b-9c85-a268931aeb72">
-Integration shows as added. I opened Node Red and ran the flow you shared and got: 
"0.4.5"

**Comment by blairlukacs** [comment]
I can move this to closed. It turns out there was a duplicate folder in my custom component config that was renamed something different so I continually missed it. Once I found this and deleted it I was able to manually add the nodered folder into my custom component and it now functions. Thank you for the help.
