### ISSUE TITLE
Requires a newer issue of home-assistant-websocket than current release??

### ISSUE THREAD

**Issue by tethlah** [zachowj/hass-node-red#212]
## Version of the custom_component

Currently using v2.2.0 but looking to update to v3.0.0

## Configuration

none

## Describe the bug

Current release of node-red-contrib-home-assistant-websocket is v0.56.1 but this requires v0.57+
There's no option in node-red to update websocket to v0.57 and the github and node-red for it has v0.56.1 as the latest release.  

## Debug log

none

**Comment by zachowj** [comment]
Currently in beta: https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.57.0-beta.1

**Comment by tethlah** [comment]
So the "release" version of the integration requires the "beta" version of the addon?  You know some of use don't run beta versions of things in a production environment right?  Common practice would have you put your companion applications in the same development branch so people who don't want to run beta versions in specific environments don't end up having dependencies that outside the stability they want to be running in that environment.

Any idea when the dependency will be out of beta?  Had I not read through everything and referenced the releases on dependencies I would have been in a precarious situation.

**Comment by tethlah** [comment]
BTW, you're doing great work, I'm meaning what I'm saying purely as a constructive criticism, not as a complaint.
