### ISSUE TITLE
Device trigger don't work after 3.0.0

### ISSUE THREAD

**Issue by Anian-igor** [zachowj/hass-node-red#213]
## Version of the custom_component
3.0.0

## Describe the bug

Device trigger stop working after upgrade to 3.0.0
I see trigger information in device logs but stopped working in node-red

**Comment by ianfretwell** [comment]
I assume that this is as per the breaking change notes:-

**Requires Home Assistant nodes version 0.57.0+**

Which would be fine if Node-Red was showing there being a version 0.57 - but it doesn't, 0.56.1 is all there is (for me).
So it just looks like a badly timed release to me - it should have been held back until 0.57 nodes were available.

**Comment by Stuke00** [comment]
> I assume that this is as per the breaking change notes:-
> 
> **Requires Home Assistant nodes version 0.57.0+**
> 
> Which would be fine if Node-Red was showing there being a version 0.57 - but it doesn't, 0.56.1 is all there is (for me). So it just looks like a badly timed release to me - it should have been held back until 0.57 nodes were available.

Same, I don't see how to install nodes 0.57

**Comment by Anian-igor** [comment]
I revert back to 2.2.0
Working well

**Comment by bscheutjens** [comment]
They released a beta of 0.57 of node-red-contrib-home-assistant-websocket. 

- In HA go to Settings -> Add-ons -> Node-RED
- Go to tab "Configuration"
- In the field "npm_packages" add "node-red-contrib-home-assistant-websocket@beta" (without the quotes)
- Restart Node-RED

This should automatically install the beta version and for me everything seems to work. Don't forget to revert this after 0.57 has actually released to prevent getting beta version in the future.

**Comment by ianfretwell** [comment]
Thanks - good to know - but...

I don't use NodeRed within HA - it's an independant Docker image...(as is HA itself)

**Comment by bscheutjens** [comment]
> Thanks - good to know - but...
> 
> I don't use NodeRed within HA - it's an independant Docker image...(as is HA itself)

Do you have access to the Node-RED configuration file itself? If so, my comment results in the following snippit in the configuration file:

```
npm_packages:
  - node-red-contrib-home-assistant-websocket@beta
```

**Comment by ianfretwell** [comment]
I do - although nothing that looks quite like you've posted - 

but for now I'm not going to edit that - I'd rather it get released on the normal channel,

Thanks.
