### ISSUE TITLE
after upgrade to 3.01 device trigger stopped working in nodered

### ISSUE THREAD

**Issue by kgiedrius** [zachowj/hass-node-red#218]
I use zigbee2mqtt and device trigger node in nodered to trigger state changes from zigbee devices. 
After upgrading to 3.0.1 - this node do not react at all.
Downgraded to 2.x version and everything works again

**Comment by zachowj** [comment]
Are you running node-red-contrib-home-assistant-websocket 0.57+?

https://github.com/zachowj/hass-node-red/releases/tag/v3.0.0

**Comment by kgiedrius** [comment]
issue with this one: https://github.com/zachowj/hass-node-red/releases/tag/v3.0.1

where to check: node-red-contrib-home-assistant-websocket ?

**Comment by zachowj** [comment]
Under manage palette in Node-RED

![image](https://github.com/zachowj/hass-node-red/assets/37859597/5097e111-7f8a-4bf0-a986-2faadfd35424)

**Comment by kgiedrius** [comment]
<img width="703" alt="image" src="https://github.com/zachowj/hass-node-red/assets/15670549/42903440-da4e-41ce-933e-96a653a31ef2">

**Comment by MJHeijster** [comment]
Not sure if this is related. I have 0.57.2 for the websocket node. I noticed that the "trigger: state" doesn't let me check the current state of a helper of type input_boolean against a boolean:
![image](https://github.com/zachowj/hass-node-red/assets/246678/28f62fcd-ed16-41c6-a5ed-598349a83c82)
If I match it against a string "on", it works. 
![image](https://github.com/zachowj/hass-node-red/assets/246678/27f52673-ffb5-417f-887d-1ebc138eb6b4)

**Comment by GoSpursGoNL** [comment]
> <img alt="image" width="703" src="https://user-images.githubusercontent.com/15670549/273368711-42903440-da4e-41ce-933e-96a653a31ef2.png">

So then you first need to upgrade that module, then update this custom integration in HACS, then stop Node-Red, restart HA, and start Node-Red. For me, that solved the problem.

**Comment by Jens-Wymeersch** [comment]
@GoSpursGoNL Hello, can you give me some tips how you configured the companion in node red ?

Thanks,
Jens
