### ISSUE TITLE
HA version 0.109 log error

### ISSUE THREAD

**Issue by vMeph** [zachowj/hass-node-red#22]
on HA version 0.109 getting the flowing error
`nodered: the '.translations' directory has been moved, the new name is 'translations', starting with Home Assistant 0.111 your translations will no longer load if you do not move/rename this`

**Comment by McGiverGim** [comment]
Maybe is a good moment to ask about translating this. It is only two phrases, but what is the correct way to do it? Make a PR with the translations? I see it difficult to maintain. 
It will be a great idea to upload it to some free web for translations, I think getlocalization closed, but maybe there are others. I use Crowdin (free for open source) but I don't know if such small project will be accepted.

**Comment by robinsmidsrod** [comment]
What about the translation web frontend that HA has for their components? Frenck mentioned in the 0.109 release notes that you don't even need to know any coding/git to use it. Can it be utilized for custom compontents, or do custom components have to setup their own service?

**Comment by McGiverGim** [comment]
Yes, I translate Home Assistant to Spanish in lokalise. I don't know if it is free but only official addons are there.

**Comment by zachowj** [comment]
Yes, there are only two strings that would need to be translated for this integration and I don't really see it increasing as almost everything UI based is handled by the NR nodes package. Something like lokalise.co, that HA uses, might be overkill but I could see about getting it set up for the NR package as well and then might as well run it for both of the projects.
