### ISSUE TITLE
Entities not available (2023.11.0 and NR 15.0)

### ISSUE THREAD

**Issue by driagi** [zachowj/hass-node-red#225]
I updated HA to 2023.11.0 and Node-Red to 15.0. After the upgrade some entities are not available in HA. Tried to do a downgrade and everything works, I created an updated clone and it doesn't work

**Comment by driagi** [comment]
I also tried the HA(2023.11.0) and Node-Red (14.6.3) configuration. Not all entities work. 
N.B.  -> I was probably wrong, but the entities (Category -> Config) don't work. Leaving it blank, it works again

**Comment by TuTunabh4** [comment]
I've met the same problem. Maybe it's because of the HA.

**Comment by driagi** [comment]
> I've met the same problem. Maybe it's because of the HA.
Check if they are CONFIG

**Comment by rlust** [comment]
What has happened to some of my NR. sensors? I am at current releases and sensors become unavailable.

**Comment by zachowj** [comment]
What version of the package are you using?

**Comment by Lateadapter** [comment]
Same here...
I did start from HA Core 2023.10.5 and NodeRed 15.0.0. After update to HA Core 2023.11.0 all within NodeRed defined entities were not anymore available in HA.
I did a downgrade to NodeRed 14.6.3 - the same.
I went back to HA Core 2023.10.5 and everything did work as before.

Again after update to HA Core 2023.11.0 (now with NodeRed 14.6.3) all entities disappeared.

The error log of HA start did show following inconsistencies:

  `Logger: homeassistant.components.sensor
  Source: helpers/entity_platform.py:507
  Integration: Sensor (documentation, issues)
  First occurred: 20:57:24 (20 occurrences)
  Last logged: 20:57:25
  
  Error adding entities for domain sensor with platform nodered
  Traceback (most recent call last):
    File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
      await asyncio.gather(*tasks)
    File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
      await entity.add_to_platform_finish()
    File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
      await self.async_internal_added_to_hass()
    File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
      raise HomeAssistantError(
  homeassistant.exceptions.HomeAssistantError: Entity sensor.e3dc_batterie_laden_kwh **cannot be added as the entity category is set to config**
  `

and

`Logger: homeassistant
Source: components/sensor/__init__.py:279
First occurred: 20:57:24 (20 occurrences)
Last logged: 20:57:25

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.e3dc_batterie_laden_kwh **cannot be added as the entity category is set to config**
`

I removed at all sensor definitions within NodeRed the category "config" and leave the field empty.
After Restart of HA all entities were acquired.

Definition of new sensor with empty category field also is working - so far solved for me.

**Comment by zachowj** [comment]
Looks like the new check was added here https://github.com/home-assistant/core/pull/101471

**Comment by 3ative** [comment]
Same....
None of my NR switches are controller-able now 🤮
![swith](https://github.com/zachowj/hass-node-red/assets/51385971/429a35f5-7575-4375-ae72-ad77019a373f)

**Comment by dgthomson** [comment]
Quick fix: in ``/custom_components/nodered/__init__.py`` lines 189 and 190, change to:

```
#        if category == "config":
#            return EntityCategory.CONFIG
```

i.e. comment these lines out, then restart. The entities reappear.
