### ISSUE TITLE
Switches stopped working in node red

### ISSUE THREAD

**Issue by driagi** [zachowj/hass-node-red#227]
Core  2023.11.1
Supervisor 2023.11.0 
Operating System 11.1
Release hass-node-red 3.1.1

The switches stopped working in node red

**Comment by zachowj** [comment]
What version of this component are you running? What part of the switches aren't working?

**Comment by driagi** [comment]
> What version of this component are you running? What part of the switches aren't working?
node-red-contrib-home-assistant-websocket 0.58.1
Now seen the update. I try to update

**Comment by zachowj** [comment]
This package is the custom component for Home Assistant. It is not the Home Assistant nodes inside Node-RED. You probably installed it via HACS. The version number is going to be something like 3.1.1. If the `nodered.trigger` service is no longer working for you. You're probably on version 2.2.0. If so then it needs to be updated to work with the HA nodes 0.57+.

**Comment by driagi** [comment]
As written at the beginning, I am on version 3.1.1. I updated node-red-contrib-home-assistant-websocket to version 0.59 and it works now

**Comment by gerione** [comment]
Node-RED Current version: 16.0.2
node-red-contrib-home-assistant-websocket 0.59.0
Core 2023.11.2
Supervisor 2023.11.3
Operating System 11.1

Once I create a switch I get 2 switches in the companion and no feedback back to Node Red
Tried to reinstall everything. Not working.

**Comment by gerione** [comment]
Somehow removing all entities and then readding it solved it.
