### ISSUE TITLE
Do you have in plan to upgrade this version of node red or i wil uninstall and work with HASS Automation?

### ISSUE THREAD

**Issue by Liionboy** [zachowj/hass-node-red#237]
17 Dec 00:40:52 - [info] Node-RED version: v3.1.0
17 Dec 00:40:52 - [info] Node.js  version: v18.18.2
17 Dec 00:40:52 - [info] Linux 6.1.63-haos x64 LE
17 Dec 00:40:54 - [info] Loading palette nodes
17 Dec 00:40:54 - [warn] [node-red-contrib-home-assistant-websocket] Node module cannot be loaded on this version. Requires: >=3.1.1 
17 Dec 00:40:56 - [info] Dashboard version 3.6.2 started at /endpoint/ui
17 Dec 00:40:59 - [warn] Missing node modules:
17 Dec 00:40:59 - [warn]  - node-red-contrib-home-assistant-websocket (0.62.2): ha_entity_filter, ha-api, ha-binary-sensor, ha-button, api-call-service, server, api-current-state, ha-device, ha-device-config, ha-entity, ha-entity-config, server-events, server-state-changed, ha-fire-event, ha-get-entities, api-get-history, ha-number, poll-state, api-render-template, ha-select, ha-sensor, ha-sentence, ha-switch, ha-tag, ha-text, ha-time, ha-time-entity, trigger-state, ha-update-config, ha-wait-until, ha-webhook, ha-zone
17 Dec 00:40:59 - [info] Removing modules from config
17 Dec 00:40:59 - [info] Settings file  : /etc/node-red/config.js
17 Dec 00:40:59 - [info] Context store  : 'default' [module=memory]
17 Dec 00:40:59 - [info] User directory : /config/
17 Dec 00:40:59 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Dec 00:40:59 - [info] Flows file     : /config/flows.json
17 Dec 00:40:59 - [info] Server now running at http://127.0.0.1:46836/
17 Dec 00:40:59 - [info] Waiting for missing types to be registered:
17 Dec 00:40:59 - [info]  - ha-entity-config
17 Dec 00:40:59 - [info]  - server
17 Dec 00:40:59 - [info]  - api-call-service
17 Dec 00:40:59 - [info]  - api-current-state
17 Dec 00:40:59 - [info]  - ha-device
17 Dec 00:40:59 - [info]  - server-state-changed
17 Dec 00:40:59 - [info]  - ha-zone
17 Dec 00:40:59 - [info]  - poll-state

**Comment by zachowj** [comment]
This is a custom component for Home Assistant it has nothing to do with your error. You need to upgrade Node-RED to get node-red-contrib-home-assistant-websocket to work.
