### ISSUE TITLE
After updating to  v3.1.3 error reemerged: object message: "ValidationError: "target.entity_id" must be an array" 

### ISSUE THREAD

**Issue by dierochade** [zachowj/hass-node-red#243]
## Version of the custom_component
3.1.3
## Configuration

```yaml
Add your logs here.
```

## Describe the bug

I did update node red and ha core to latest. Until updating node red companion via hacs everything went fine. Now I get the error 

{"topic":"input_number.thermo_5_scheduled_temp","payload":"2024-01-09T21:02:51.480Z: {\"domain\":\"input_number\",\"service\":\"set_value\",\"target\":{\"entity_id\":\"input_number.thermo_5_scheduled_temp\"},\"data\":{\"value\":15}}","_msgid":"2890f4fe4eb00245","error":{"message":"ValidationError: \"target.entity_id\" must be an array","source":{"id":"73d3fe87f44d06f9","type":"api-call-service","name":"assign scheduled temps to input.helper","count":1},"stack":"ValidationError: \"target.entity_id\" must be an array"},"filename":"/homeassistant/www/nodered/log_errors_thermostats.txt"}

in call service nodes again?

**Comment by zachowj** [comment]
Are you running at least [0.62.3](https://github.com/zachowj/node-red-contrib-home-assistant-websocket/releases/tag/v0.62.3) of the HA nodes?

**Comment by dierochade** [comment]
your right, in the palette manager it shows 0.62.2

but i understood one should not update manually, i am running node red addon Current version: 17.0.1, which should upgrade to 0.62.3 according to changelog?

**Comment by zachowj** [comment]
> but i understood one should not update manually

That's probably a good idea. The addon v17.0.1 should come with [0.62.3](https://github.com/hassio-addons/addon-node-red/blob/dba28a26566b576a3da4afcb790f5f44c836c132/node-red/package.json#L19)

**Comment by dierochade** [comment]
Was able to fix it by manually adjust the version in the package.json in the addon_config folder of ha. 

Thank you for your time and assistance. Seems odd to get kinda forth level support, but much appreciated. 

Keep going+all the best
