### ISSUE TITLE
How to start Node-Red for 0.110.1?

### ISSUE THREAD

**Issue by anglrus** [zachowj/hass-node-red#25]
## Configuration

I use last version and did following steps:
1. Setup module and have instruction that it is necessary to use Integration
2. Setup integration
3. Open port 1880 on router

It all. I saw many video instructions, but can't find button open web, start and other.
How can I start it?

Add your logs here.

```

## Describe the bug
A clear and concise description of what the bug is.


## Debug log

<!-- To enable debug logs check this https://www.home-assistant.io/components/logger/ -->

```text

Add your logs here.

```

**Comment by zachowj** [comment]
This the repo for the NR custom component for HA not Node-RED.
