### ISSUE TITLE
Sudden change of entity name

### ISSUE THREAD

**Issue by driagi** [zachowj/hass-node-red#252]
Some entities created in node red have changed their name to HA. For example sensor.nr_stufetta_totale has become sensor.stufetta_totale. The variables that have changed names are those Class State -> Total

The problem occurred when switching from Core 2024.1.3 to 2024.2.0
Node-Red 17.0.6
HA OS: 11.5
Hass-node-red: v3.13
node-red-contrib-home-assistant-websocket: 0.62.3

Once the entities were recreated, they changed names again (after half a day). 

![Cattura](https://github.com/zachowj/hass-node-red/assets/74871092/c3b45fa2-3318-4bfe-b748-dc1951317c58)
![Cattura2](https://github.com/zachowj/hass-node-red/assets/74871092/cf6b8902-c242-4c95-9fd9-55ca30a58b22)

If anything is needed, within my capabilities, I am obviously available for information or tests.

**Comment by driagi** [comment]
![image](https://github.com/zachowj/hass-node-red/assets/74871092/95a33811-d0c1-4dc2-b25d-984e5dff587c)

**Comment by LittleLama** [comment]
I confirm the issue, everything was unavailable on the HASS UI after update. I had to rename every entity.

**Comment by driagi** [comment]
@zachowj . With subsequent updates, it never happened again. For me it can also be closed
