### ISSUE TITLE
Nodered 18 not working in HA

### ISSUE THREAD

**Issue by sdavides** [zachowj/hass-node-red#278]
### Describe the bug

I can no longer add new entities, I don’t see it in the sensor “Entity congif” menu.
I had never seen “none”.

I also tried with the "+" button but the screen doesn't change.

### Screenshots

![immagine](https://github.com/zachowj/hass-node-red/assets/31100253/79e4fda2-a8ea-4655-90bc-840a8a32c551)

### Environment Information

NodeRed version: 18.0.0

HA
Core 2024.6.4
Supervisor 2024.06.0

**Comment by sdavides** [comment]
I reverted to the old version 17.0.13 (nodered 3).
With version 18 (nodered 4) I didn't understand how to do it.

**Comment by synekvl** [comment]
@sdavides: I have also significant problem with a combination of HA 2024.6.x and NodeRed version 17.0.12-18.0.0.  All my Home assistant entities are now dead, I have a info "This node requires [Node-RED custom integration version 1.1.0+ ....." in node's properties (with installed NR-companion v4.0.0 and websocket 0.65.0). There is something wrong either with NR installation (I uninstalled NR and installed back "fresh" v18.0.0) and/or this integration. I would like to try older NR version i.e. 17.0.10 but I don't know how to install it. Any hints ?

**Comment by sdavides** [comment]
restore only  "NodeRed" component from a HA backup or install manually https://github.com/hassio-addons/addon-node-red/releases

**Comment by sdavides** [comment]
The new version really has bugs, why isn't anyone talking about it?

**Comment by synekvl** [comment]
@sdavides: my HA installation is supervised version running on VM. Can you help me how to make installation of older NodeRed version which I downloaded from github ? I have tried to install it with path to relevant repository but it is not, unfortunately, the proper way...

**Comment by sdavides** [comment]
I also supervised, don't you have an old backup??

Manual:
    Download ZIP with the older add-on version
    Copy it into /addons and unzip 
    Go to add-on store, open the three-dots menu (top right corner) and click Check for updates
    You should see new Local add-ons section
    Install the add-on

![immagine](https://github.com/zachowj/hass-node-red/assets/31100253/85d2d879-1d47-4803-bad0-aed0d9845514)

**Comment by sdavides** [comment]
why did you close my issue? the main problem is not solved

**Comment by synekvl** [comment]
@sdavides  I have followed your instruction making the folder /addons, downloaded nodered 17.0.12 zip and unziped content into addons under another subfolder named nodered. After this I went to HA menu -> add-on -> add-on store -> three dots -> check for updates, but unfortunately I can't get Local add-ons section on the screen. Till may everything worked more or less fluently but then the changes to nodered and finally to HA 2024.6 made the system lazy with lovelace card history unavailable and so on. I'm little bit scared to make re-installation of the whole system but...

**Comment by sdavides** [comment]
you have to copy the "nodered" folder inside the zip, not the all contents of the entire zip

**Comment by synekvl** [comment]
![addon](https://github.com/zachowj/hass-node-red/assets/42292671/ce221c69-420e-41a3-96af-3922b04bec20)

This screenshot looks like yours but still nothing after Check for updates in Add-on Store screen.

I have just downloaded fresh new HA NR v 18.0.2 but there is no change. This is an extract from NR log:

![nrlog](https://github.com/zachowj/hass-node-red/assets/42292671/1e4e987f-3617-4967-9666-65a40bcaed86)

**Comment by sdavides** [comment]
I don't know why you don't see it.

"integration not loaded" I also see it with any version, but only at start, then it works correctly

**Comment by synekvl** [comment]
I keep HA backups for four days only, so that is not the way :-(

**Comment by sdavides** [comment]
???
what is the meaning of a backup for 4 days only?

**Comment by synekvl** [comment]
I make full backup everyday and keep them four days back, so now I have backup from 2.7, 1.7, 30.6 and 29.6 only. It is something to be considered for future.

**Comment by sdavides** [comment]
your strategy is wrong, what is the meaning of taking backup every day??

You have to make a backup with everything working and that's it, then every time you update something you check that it works and make a new backup.

You can delete the .db statistics file to save space.

**Comment by synekvl** [comment]
the main aim was to have a data backup. I did not need program backup before. That's the reason I wrote I have to reconsider the backup scheme for future...

**Comment by sdavides** [comment]
I didn't understand "I did not need program backup before"

you have to make a complete backup from the homeassistant menu, which saves everything

**Comment by synekvl** [comment]
I meant that until now everything worked not as sharm but I had no problem within last 8-9 years so I had no "reason" to think seriously about backup. My fault, of course.

**Comment by sdavides** [comment]
I could send you my partial nodered backup, so you can restore it from the backup menu, but I need to remove the sensitive information first
