### ISSUE TITLE
Nodered 18 not working in HA 

### ISSUE THREAD

**Issue by sdavides** [zachowj/hass-node-red#280]
### Describe the bug

I can no longer add new entities, I don’t see it in the sensor “Entity congif” menu.
I had never seen “none”.

I also tried with the "+" button but the screen doesn't change.

### Screenshots

![342080387-79e4fda2-a8ea-4655-90bc-840a8a32c551](https://github.com/zachowj/hass-node-red/assets/31100253/21a5efb4-5a81-4d2d-ad2d-617a1317df3f)

### Environment Information

NodeRed version: 18.0.0

HA
Core 2024.6.4
Supervisor 2024.06.0

**Comment by jeroenmert** [comment]
Hi I have exactly the same issue.

**Comment by sdavides** [comment]
revert nodered 17 form ha backup.

Incredible, nodered 18 still bugged

**Comment by jeroenmert** [comment]
Yes I tried also to update to HomeAssistant V2024.7 but than all my node red created entities from companion are lost his connection. So i will wait to update node red and homeassistant because both giving issues with node red.

**Comment by zachowj** [comment]
Node-RED doesn't have version 18. The latest release is [4.0.2](https://github.com/node-red/node-red/releases/tag/4.0.2).

Use the diagnostics button to get the installed version https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html

**Comment by guibom** [comment]
> Node-RED doesn't have version 18. The latest release is [4.0.2](https://github.com/node-red/node-red/releases/tag/4.0.2).
> 
> Use the diagnostics button to get the installed version https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html

It's version 18 of the HA Node-Red add-on, that updates to Node-Red 4.0.2

**Comment by zachowj** [comment]
Check your browser console for errors that might be blocking the javascript.

It's working as expected for me on Node-RED 4.0.2

![firefox_h6gDm83QKG](https://github.com/zachowj/hass-node-red/assets/37859597/8bdaca3d-d38f-410e-a073-db2d8285c192)

**Comment by sdavides** [comment]
> Node-RED doesn't have version 18. The latest release is [4.0.2](https://github.com/node-red/node-red/releases/tag/4.0.2).
> 
> Use the diagnostics button to get the installed version https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html

???

![immagine](https://github.com/zachowj/hass-node-red/assets/31100253/74183f3f-c9f9-48ba-bf6f-e8cd3350d778)

**Comment by sdavides** [comment]
using the "+" overwrites an existing entity, it is impossible to create a new entity.

**Comment by zachowj** [comment]
> > Node-RED doesn't have version 18. The latest release is [4.0.2](https://github.com/node-red/node-red/releases/tag/4.0.2).
> > Use the diagnostics button to get the installed version https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html
> 
> ???

Your screenshot shows the Node-RED addon, not the Home Assistant nodes version you installed in Node-RED. That's why I asked for the information from the diagnostic button.

Here is it working and not overwriting the selected entity with version 0.65.1 of the Home Assistant nodes (node-red-contrib-home-assistant-websocket)

![firefox_Qjlg5d9ptE](https://github.com/zachowj/hass-node-red/assets/37859597/620573a3-5035-470d-88a2-e1eae12fc20b)

**Comment by jeroenmert** [comment]
> > > Node-RED doesn't have version 18. The latest release is [4.0.2](https://github.com/node-red/node-red/releases/tag/4.0.2).
> > > Use the diagnostics button to get the installed version https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html
> > 
> > 
> > ???
> 
> Your screenshot shows the Node-RED addon, not the Home Assistant nodes version you installed in Node-RED. That's why I asked for the information from the diagnostic button.
> 
> Here is it working and not overwriting the selected entity with version 0.65.1 of the Home Assistant nodes (node-red-contrib-home-assistant-websocket)
> 
> ![firefox_Qjlg5d9ptE](https://private-user-images.githubusercontent.com/37859597/346469236-620573a3-5035-470d-88a2-e1eae12fc20b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjQ1MDAsIm5iZiI6MTcyMDQyNDIwMCwicGF0aCI6Ii8zNzg1OTU5Ny8zNDY0NjkyMzYtNjIwNTczYTMtNTAzNS00NzBkLTg4YTItZTFlYWUxMmZjMjBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3MzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzhiYmMxY2UwNGE1YmY2MmI5YTgzYWEzZDQ4ZmEyMzJiZWNhOTVmN2Q1ODg5ZTYwYjE3NTY4MmE1ODc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwWgA_ooZR78CVEA6vcwSorRnWFATbiq8msnxy6zpdE) [ ![firefox_Qjlg5d9ptE](https://private-user-images.githubusercontent.com/37859597/346469236-620573a3-5035-470d-88a2-e1eae12fc20b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjQ1MDAsIm5iZiI6MTcyMDQyNDIwMCwicGF0aCI6Ii8zNzg1OTU5Ny8zNDY0NjkyMzYtNjIwNTczYTMtNTAzNS00NzBkLTg4YTItZTFlYWUxMmZjMjBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3MzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzhiYmMxY2UwNGE1YmY2MmI5YTgzYWEzZDQ4ZmEyMzJiZWNhOTVmN2Q1ODg5ZTYwYjE3NTY4MmE1ODc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwWgA_ooZR78CVEA6vcwSorRnWFATbiq8msnxy6zpdE) ](https://private-user-images.githubusercontent.com/37859597/346469236-620573a3-5035-470d-88a2-e1eae12fc20b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjQ1MDAsIm5iZiI6MTcyMDQyNDIwMCwicGF0aCI6Ii8zNzg1OTU5Ny8zNDY0NjkyMzYtNjIwNTczYTMtNTAzNS00NzBkLTg4YTItZTFlYWUxMmZjMjBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3MzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzhiYmMxY2UwNGE1YmY2MmI5YTgzYWEzZDQ4ZmEyMzJiZWNhOTVmN2Q1ODg5ZTYwYjE3NTY4MmE1ODc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwWgA_ooZR78CVEA6vcwSorRnWFATbiq8msnxy6zpdE) [ ](https://private-user-images.githubusercontent.com/37859597/346469236-620573a3-5035-470d-88a2-e1eae12fc20b.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MjQ1MDAsIm5iZiI6MTcyMDQyNDIwMCwicGF0aCI6Ii8zNzg1OTU5Ny8zNDY0NjkyMzYtNjIwNTczYTMtNTAzNS00NzBkLTg4YTItZTFlYWUxMmZjMjBiLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDA3MzY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhMzhiYmMxY2UwNGE1YmY2MmI5YTgzYWEzZDQ4ZmEyMzJiZWNhOTVmN2Q1ODg5ZTYwYjE3NTY4MmE1ODc3MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rwWgA_ooZR78CVEA6vcwSorRnWFATbiq8msnxy6zpdE)

Hi Thank you for your small video. It works perfect.

**Comment by sdavides** [comment]
with the latest update yesterday v4.0.1 it works, before it didn't work.
