### ISSUE TITLE
Energy entities stopped working in the Energy panel with version 4.01

### ISSUE THREAD

**Issue by driagi** [zachowj/hass-node-red#288]
### Describe the bug

After updating to version 4.0.1, the Energy panel stopped working (undefined entity)
My configuration:
Node-Red Companion: 4.01
Core: 2024.7.2
Supervisor: 2024.06.2
Operating System: 12.4

### To Reproduce

1. Create a energy entity 
2. Add Entity to Energy panel

### Screenshots

![image](https://github.com/user-attachments/assets/e00aac9f-3491-42a9-9551-3d879cdda6f0)
![image](https://github.com/user-attachments/assets/fb48c58e-8ec5-429f-a9eb-8872a0cbe285)
![image](https://github.com/user-attachments/assets/912f14a6-cd7a-4408-9b5a-d36ab9f7641c)

### Environment Information

Version: 0.65.1

Home Assistant version: 2024.7.2
Companion version: 4.0.1

Node-RED version: 4.0.2
Docker: yes
Add-on: no

Node.js version: v18.20.3 arm64 linux
OS: Linux 6.6.31-haos-raspi arm64

**Comment by zachowj** [comment]
What does the state for those two entities show in the developers tools in HA?

**Comment by driagi** [comment]
They don't exist...while in Node-red they seem regularly registered. For example:
![image](https://github.com/user-attachments/assets/789794ed-9293-43d3-bf53-71be36863712)
![image](https://github.com/user-attachments/assets/287623b6-a77c-42d1-8753-937c6c2d40fb)

**Comment by driagi** [comment]
They don't exist, but I think they've changed names.
For example: from sensor.nr_consumo_totale_2 to sensor.consumo_totale
it seems to have changed to the Friendly name

![image](https://github.com/user-attachments/assets/1ba4935c-7c27-4cfc-90da-8c7430b5def6)

**Comment by driagi** [comment]
Yes, I tested it and confirm that it takes the form sensor.friendlyname

![image](https://github.com/user-attachments/assets/53952043-6dd1-41be-837e-12971b69b49a)

![image](https://github.com/user-attachments/assets/75f33f1c-c3ee-4ee1-83b9-f08701e96aef)

**Comment by zachowj** [comment]
The first time you create an entity from NR it will attempt to create an entity ID from the friendly name field. If the friendly name field is blank the entity id will default to `sensor.nodered_<node id >`. After the entity has been created in HA for the first time, the friendly name field controls only the friendly name in HA. It will not change the entity ID field. That has to be done through HA.

**Comment by driagi** [comment]
But the entity name changed on day 7 after the update (4.0.1 Comapanion version). I didn't create or change anything, i in fact the energy panel worked well for months until day 7

**Comment by PaviAN31** [comment]
I have Node-RED version 4.0.2 and I solved reading via API from SolarX in the following way:
1. API call every 2 minutes. (max. API is 10 queries per 1 min)
2. Querying the API with the "http request" block
3. transfer of individual data from the API to specific devices in HA via the "sensor" block - each value in a separate block

This solution works very well, I did it about a week ago and I don't have any problems with it so far, all values ​​are transferred correctly, except that HA shows data at 5-minute intervals, so I think that it would be possible to easily reduce API polling to 1x every 4- 5 min.
The green "debug" blocks are only for testing in case of read failure

![obraz](https://github.com/user-attachments/assets/c84cbd94-e6a3-46c9-beaa-6e878b8780ab)
![obraz](https://github.com/user-attachments/assets/87cf8473-fa3f-416a-bf6d-bc909a8a0f16)
![obraz](https://github.com/user-attachments/assets/18409153-c222-4495-97eb-72a90840c20b)
![obraz](https://github.com/user-attachments/assets/221eb806-143b-49e6-b780-15c18b1e034b)
![obraz](https://github.com/user-attachments/assets/d0e51f6b-a659-42a0-8d4c-8cd9cc5eceeb)
![obraz](https://github.com/user-attachments/assets/4b87ba9a-5069-4e4b-8bad-25bdc516e046)
![obraz](https://github.com/user-attachments/assets/201465cc-3d80-4513-a0bd-3cca4f8b8fd4)
![obraz](https://github.com/user-attachments/assets/0106caf5-158c-47ab-9456-52d237c67768)
![obraz](https://github.com/user-attachments/assets/dc866c6b-d4dc-4615-920f-0fd5392c35ed)

**Comment by driagi** [comment]
Solved by renaming
