### ISSUE TITLE
Node Red Companion integration bug

### ISSUE THREAD

**Issue by Naro90029** [zachowj/hass-node-red#297]
### Describe the bug

At the bottom of node settings it says “Expose as” with a list, edit, and + button next to it. When using the + button to add to the list, it doesn’t add the created expose to the list so that I can disable and enable the nodes from HA. 
However I have noticed that it does create entities; but the delete button doesn’t work to delete the entities.

### Environment Information

None

**Comment by zachowj** [comment]
Post your setup information <https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html>

**Comment by Naro90029** [comment]
> Post your setup information <https://zachowj.github.io/node-red-contrib-home-assistant-websocket/guide/diagnostics.html>

I have put all that is needed to explain the issue, I can also put images if needed but don't want to share unnecessary information; also the issue doesn't produce any errors to get debug data on it.
Just doesn't add to the list when I create new "expose as" items.
