### ISSUE TITLE
Node-Red Update? Changes Device Names

### ISSUE THREAD

**Issue by HEGarrard** [zachowj/hass-node-red#305]
### Describe the bug

I installed an update to Node-Red on Home Assistant and it appears there was a "revamp" of the edit method. Although all of my flows seemed to work properly, when I clicked on, for example "CALL SERVICE" node my named devices were all replaced with a series of numbers and letters. When I tried to add a new device - I would start typing the "name" of the device to search for it and node-red was unable to find the device.

I have attached a screenshot of one of the edit screens. Seems like a totally new revamp of the edit screen. When I would click on the "add device" I was unable to SEARCH for any devices or ADD any devices.

I had updated all of the following to these versions - when I noticed the issue ...

HA to 2024.9.3
Node-Red to 18.1.1
Node-Red Companion: v4.1.1

Because I was having issues with editing and adding new flows, I restored an old backup to get back to where I was before the Node-Red update.

Any ideas? Was the update the issues?

I restored a previous backup to the following and all seems "normal"
Currently Running:
HA: 2024.9.2
Node-Red: 18.0.5
Node-Red Companion: v4.1.0

[Node-Red.pdf](https://github.com/user-attachments/files/17229612/Node-Red.pdf)

### Expected behavior

I expected to see my Device "names" and not as a long alpha numeric description.  

When I click on a "Call Service" to edit or add a new "Call Service" - when I use the editor to ADD a device, I start typing the name of the Device and no Devices populate,  In the attached, I have a couple of devices which have "SPOT" in their name.  I would have expected that as I start typing SPOT that devices would appear that match.

[Node_red Edit Issues.pdf](https://github.com/user-attachments/files/17229701/Node_red.Edit.Issues.pdf)

[flows.json](https://github.com/user-attachments/files/17229731/flows.json)

### Example Flow

```json
[{"id":"ea6eb78c1fb68199","type":"sun-event-inject","z":"673992299f8cfca0","name":"Sunset - Lights On","latitude":"38.918960","longitude":"-87.693466","event":"sunsetStart","offset":"-1200","injectEventTimesAfterStartup":false,"x":130,"y":500,"wires":[["9d302dc0f4e2f101","7077f7b8f022d501"]]},{"id":"9d302dc0f4e2f101","type":"api-call-service","z":"673992299f8cfca0","name":"Back - Fire Pit String (25%)","server":"8727e144.d81df","version":7,"debugenabled":false,"action":"light.turn_on","floorId":[],"areaId":[],"deviceId":["5588b9c4da4185519f23f260094444b5"],"entityId":[],"labelId":[],"data":"{\"brightness_pct\":25}","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"light","service":"turn_on","x":420,"y":460,"wires":[[]]},{"id":"7077f7b8f022d501","type":"api-call-service","z":"673992299f8cfca0","name":"Back - GR Porch Table Lamp","server":"8727e144.d81df","version":7,"debugenabled":false,"action":"switch.turn_on","floorId":[],"areaId":[],"deviceId":["582f18fcc0930eda0e059d3f7729568f"],"entityId":[],"labelId":[],"data":"","dataType":"jsonata","mergeContext":"","mustacheAltTags":false,"outputProperties":[],"queue":"none","blockInputOverrides":false,"domain":"switch","service":"turn_on","x":420,"y":540,"wires":[[]]},{"id":"8727e144.d81df","type":"server","name":"Home Assistant","addon":true,"rejectUnauthorizedCerts":true,"ha_boolean":"","connectionDelay":false,"cacheJson":false,"heartbeat":false,"heartbeatInterval":"","areaSelector":"friendlyName","deviceSelector":"friendlyName","entitySelector":"friendlyName","statusSeparator":"","statusYear":"hidden","statusMonth":"hidden","statusDay":"hidden","statusHourCycle":"default","statusTimeFormat":"h:m","enableGlobalContextStore":false}]
```

### Environment Information

Unable to get this information.

**Comment by zachowj** [comment]
Are you access the Node-RED UI throught the Home Assistant UI? What if you connect directly to the Node-RED UI on port 1880?

**Comment by HEGarrard** [comment]
I am connecting to Node-Red through the Home Assistant interface.  
I used an old backup to get back to a "working system" and have disabled the node-red updates.
I will back everything up again and then reinstall all of the updates and see if the issue occurs again.  If so, I will connect through Port 1880 and see if the issue is there as well.

**Comment by HEGarrard** [comment]
Ok ... I Updated NODE-Red and I have the same issue.
I have taken several screenshots ...

From Home Assistant User Interface ...
HAUI - Showing Node-Red flows after update
HAUI Edit - Editor Open
HAUI Update - Message after selecting Update Nodes
HAUI Edit 2 - Editor Open after Update Node

From Home Assistant PORT 1880...
PORT1880 - Showing Node-Red flows after update
PORT 1880 UPDATED - After going through the node update steps in the Home Assistant UI ... NO FLOWS appear Using Port 1880.

[HAUI.pdf](https://github.com/user-attachments/files/17238451/HAUI.pdf)
[HAUI EDIT.pdf](https://github.com/user-attachments/files/17238455/HAUI.EDIT.pdf)
[HAUI UPDATE.pdf](https://github.com/user-attachments/files/17238456/HAUI.UPDATE.pdf)
![HAUI EDIT 2](https://github.com/user-attachments/assets/2af1857c-83ed-4133-ba3c-8e1611ced60f)

[PORT1880.pdf](https://github.com/user-attachments/files/17238457/PORT1880.pdf)
[PORT1880 UPDATED.pdf](https://github.com/user-attachments/files/17238462/PORT1880.UPDATED.pdf)

**Comment by HEGarrard** [comment]
UPDATE:  I just found that Node-Red must have auto updated again.  If I use the HA User Interface - I still have the same issue.  However, if I go to PORT1880, the devices appear as their friendly name AND I can add devices using the search mode and the FRIENDLY NAMES are displayed.

[HAUI EDIT 2.pdf](https://github.com/user-attachments/files/17251206/HAUI.EDIT.2.pdf)

[PORT1880 EDIT.pdf](https://github.com/user-attachments/files/17251207/PORT1880.EDIT.pdf)

**Comment by zachowj** [comment]
WebSocket communication appears to be rejected when accessing Node-RED through an iframe in the Home Assistant UI rather than directly via port 1880. This issue affects inject nodes, the debug window, and the new issues feature, preventing proper communication between the Node-RED backend and UI.

Until this is resolved or the root cause for the WebSocket issue is identified, I recommend accessing Node-RED directly on port 1880.

Related issues for tracking:
- https://github.com/hassio-addons/addon-node-red/issues/1938
- https://github.com/zachowj/node-red-contrib-home-assistant-websocket/issues/1480

**Comment by GeorgeWatch** [comment]
Hi, I also have the same problem. I found that when I open the editor in one HA tab, I duplicate the tab and find Settings -> Plugins -> Node-Red -> Restart and the editor comes to life ....
I previously googled that I should update everything in the palette manager.
17 Oct 17:06:42 - [info] Node-RED version: v4.0.3
17 Oct 17:06:42 - [info] Node.js version: v18.20.4
17 Oct 17:06:42 - [info] Linux 6.6.31-haos-raspi arm64 LE
17 Oct 17:06:42 - [info] Loading palette nodes
17 Oct 17:06:45 - [info] Node-RED Contrib Theme Collection version: v4.0.11
17 Oct 17:06:52 - [info] Dashboard version 3.6.5 started at /endpoint/ui
17 Oct 17:06:53 - [info] node-red-contrib-home-assistant-websocket v0.74.1 nodes initialized
17 Oct 17:06:54 - [info] Settings file : /etc/node-red/config.js
17 Oct 17:06:54 - [info] Context store : 'default' [module=memory]
17 Oct 17:06:54 - [info] User directory : /config/
17 Oct 17:06:54 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Oct 17:06:54 - [info] Flows file : /config/flows.json
17 Oct 17:06:54 - [info] Server now running at http://127.0.0.1:46836/
17 Oct 17:06:54 - [info] Starting flows

translate google :-)
