### ISSUE TITLE
STATE_UNLOCKED was used from nodered, this is a deprecated constant

### ISSUE THREAD

**Issue by DirkMu** [zachowj/hass-node-red#307]
### Describe the bug

I am on HA Core 2024.10 and get the following warning:

```
(ImportExecutor_0) [homeassistant.const] STATE_UNLOCKED was used from nodered, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'nodered' custom integration

(MainThread) [homeassistant.helpers.frame] Detected that custom integration 'nodered' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/nodered/switch.py, line 62: platform.async_register_entity_service(, please create a bug report at https://github.com/zachowj/hass-node-red/issues

```

### To Reproduce

Restart HA
Maybe 2024.10 required

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.10.0
Companion version: 4.1.1

Node-RED version: 4.0.3
Docker: yes
Add-on: no

Node.js version: v20.17.0 x64 linux
OS: Linux 4.4.302+ x64

**Comment by Guenni9** [comment]
Thank You!

The first issue is gone with 4.12-binary_sensor.py, but

`(ImportExecutor_0) [homeassistant.const] STATE_UNLOCKED was used from nodered, this is a deprecated constant which will be removed in HA Core 2025.10. Use LockState.UNLOCKED instead, please report it to the author of the 'nodered' custom integration`

still occurs for me. Any hint?

**Comment by Guenni9** [comment]
see also #296

**Comment by DirkMu** [comment]
Yes, 4.12 has not been released yet.
