### ISSUE TITLE
Unknown state at restart

### ISSUE THREAD

**Issue by Tathar** [zachowj/hass-node-red#310]
### Describe the bug

HomeAssistant entities created from node red have an unknown state when restarting HomeAssistant

### To Reproduce

1: Create an enite from Node Red
2: Push a value into it
3: restart HomeAssistant
4: This entity now has an unknown value

### Environment Information

Version: 0.73.0

Home Assistant version: 2024.10.1
Companion version: 4.1.1

Node-RED version: 4.0.3
Docker: yes
Add-on: 18.1.1

Node.js version: v18.20.4 x64 linux
OS: Linux 6.6.46-haos x64

**Comment by zachowj** [comment]
If you're referring to a binary sensor or sensor entity, do you have the "Resend state and attributes" option selected in the entity configuration?
