### ISSUE TITLE
NR stop to evaluate template with notify service

### ISSUE THREAD

**Issue by ceinmart** [zachowj/hass-node-red#313]
### Describe the bug

I have a notify service setup  with this message where uses template: 

```
"{"message":"{{=<% %>=}}Finalizou lavagem as {{now().strftime('%I:%M%p')}}","title":"TESTE Lavadora 8kg","data":{"group":"Lavadora-8kg","tag":"Lavadora-8kg","channel":"Lavanderia","importance":"min","icon_url":"http://xxxx/local/washing-machine.png","notification_icon":"mdi:washing-machine","media_stream":"alarm_stream"}}"

```
From a few versions ago, the evaluate of the template stopped to work.

Where they send the template code instead the result.

What I notice is this `{{=<% %>=}}` script on my message, I really don't remember to put this when I create this flow. 
Also I didn't found any documentation about what this code means.
Not sure if something change and automatically  this code was added. 
Looking the release notes found nothing.

### To Reproduce

Setup a notification service to an android on H.A. and on they message use jinja template like mine.

### Expected behavior

Evaluate the template, how works before.

### Screenshots

Below is the print of two example, first one was sent using home assistant developer tab / actions.
The second one was sent using nodered.

![image](https://github.com/user-attachments/assets/2894e70f-3015-4cc8-ad10-0a8a1ba01ced)

How I send the test thru H.A.
![image](https://github.com/user-attachments/assets/7b029c71-bb62-4cf8-92a2-0a9adcfcf688)

If I remove the code `{{=<% %>=}}` the template on my message isn't evaluated and the code just gone: 
![image](https://github.com/user-attachments/assets/ecac4b14-11ad-42e5-8a7a-8ffcc4b2478d)
If I try to use this code on H.A. interface, give an error and don't send the notification.

### Example Flow

```json
[
    {
        "id": "c620924663c6e03a",
        "type": "api-call-service",
        "z": "b831912e9175cd8d",
        "name": "Envia msg",
        "server": "1b9122517452bd28",
        "version": 5,
        "debugenabled": false,
        "domain": "notify",
        "service": "mobile_app_sm_a725m",
        "areaId": [],
        "deviceId": [],
        "entityId": [],
        "data": "{\"message\":\"{{=<% %>=}}Finalizou lavagem as {{now().strftime('%I:%M%p')}}\",\"title\":\"TESTE Lavadora 8kg\",\"data\":{\"group\":\"Lavadora-8kg\",\"tag\":\"Lavadora-8kg\",\"channel\":\"Lavanderia\",\"importance\":\"min\",\"icon_url\":\"http://xxxxx/local/washing-machine.png\",\"notification_icon\":\"mdi:washing-machine\",\"media_stream\":\"alarm_stream\"}}",
        "dataType": "json",
        "mergeContext": "",
        "mustacheAltTags": false,
        "outputProperties": [],
        "queue": "none",
        "x": 470,
        "y": 100,
        "wires": [
            []
        ]
    },
    {
        "id": "1b9122517452bd28",
        "type": "server",
        "name": "Home Assistant",
        "version": 5,
        "addon": false,
        "rejectUnauthorizedCerts": true,
        "ha_boolean": "y|yes|true|on|home|open",
        "connectionDelay": true,
        "cacheJson": true,
        "heartbeat": false,
        "heartbeatInterval": "30",
        "areaSelector": "friendlyName",
        "deviceSelector": "friendlyName",
        "entitySelector": "friendlyName",
        "statusSeparator": ": ",
        "statusYear": "hidden",
        "statusMonth": "short",
        "statusDay": "numeric",
        "statusHourCycle": "default",
        "statusTimeFormat": "h:m",
        "enableGlobalContextStore": false
    }
]
```

### Environment Information

Version: 0.62.3

Home Assistant version: 2024.10.1
Companion version: 4.1.1

Node-RED version: 4.0.5
Docker: yes
Add-on: no

Node.js version: v20.18.0 arm64 linux
OS: Linux 6.6.32-current-meson64 arm64

**Comment by zachowj** [comment]
Home Assistant has removed support for templates in the notification domain.

You can refer to the change here:  
<https://github.com/home-assistant/core/pull/122820>

**Comment by zachowj** [comment]
You can modify this to work with Node-RED by handling the template rendering on the Node-RED side and sending the complete message directly to Home Assistant, rather than relying on Home Assistant to process the template.

Change the data field type to JSONata (J: Expression) and use:

```json
"message": "Finalizou lavagem às " & $moment().format("h:mmA")
```

**Comment by ceinmart** [comment]
Thanks @zachowj , works perfectly!

Please, just give one more tip, where I can found the documentation bout the available functions? 
I looked at https://docs.jsonata.org/ , but there is a very superficial documentation, this function `$moment` isn't documented there.
I'm looking what is the options to format the date/time .
