### ISSUE TITLE
Stop working in HA Core 2025.9

### ISSUE THREAD

**Issue by dymeq** [zachowj/hass-node-red#325]
### Describe the bug

Hi. Can you resolve this problem? "Detected that custom integration 'nodered' registers an entity service with a non entity service schema which will stop working in HA Core 2025.9 at custom_components/nodered/switch.py, line 62: platform.async_register_entity_service"

### Environment Information

I don't know

**Comment by N3rdix** [comment]
this is already fixed with #312. Just update to the newest version.
