### ISSUE TITLE
Configuration | Integration is not working 

### ISSUE THREAD

**Issue by kzim200** [zachowj/hass-node-red#33]
HA Version:  .114.0
Node Red:  Installed via SuperVisor Add-on Store Version 7.0.0
Installed Node-Red Integration via Hacs , restarted 
Version of the custom component (via const.py) VERSION = "0.4.4"

I am unable to add the Node-Red integration, and nothing related to Node-red is in the logs
I have tried removing the custom component of Node-Red from Hacs and reinstalling it, but there is no difference, even after numerous restarts.

The files in custom_components/nodered match the repo.  The translations folder exists as well.

Thank you

**Comment by kzim200** [comment]
Well, it finally showed up.  Today, I am able to add the integration.  Strange as I changed nothing on my system.

**Comment by LongDono** [comment]
Same here. I had to wait until the next day. Readme.md should be updated so the instructions let people know they will need to wait.  :)
