### ISSUE TITLE
This is a confusing integration

### ISSUE THREAD

**Issue by arretx** [zachowj/hass-node-red#35]
I already have the NodeRED integration installed, and I'm looking at a node called "entity" which points to needing this custom component installed.  I have this custom component installed from HACS, but I keep getting errors in NodeRED stating that 

"Node-RED custom integration needs to be installed in Home Assistant for this node to function correctly."

The instructions regarding installing this point to manipulating the core NodeRED integration while also stating that it needs to be installed via HACS. 

???

**Comment by zachowj** [comment]
Did you do step [#3](https://github.com/zachowj/hass-node-red/blob/master/info.md#installation)?

Are your HA showing that it is loading in on boot?

**Comment by arretx** [comment]
It's step 7 on the page I was reading. 

https://github.com/zachowj/hass-node-red

Steps 1-6 seem superfluous.  Aren't these completed by using the HACS installation method?  I'm not sure how I would have found the page you pointed me to that has step 3 on it...

It's possible that I'm just dumb as a box of rocks.  ;)..  

Thank you.  The error is gone and it seems to be connecting to HA correctly.  I'll play with it now.

**Comment by zachowj** [comment]
It's the page that shows when you're installing this from HACS
