### ISSUE TITLE
Error: "Node-RED custom integration needs to be installed"

### ISSUE THREAD

**Issue by jb901** [zachowj/hass-node-red#37]
## Configuration

```yaml

HASS OS v4.12
Homeassistant 0.114.4
Node-Red v7.1.0
hass-node-red v0.4.4
```

## Describe the bug
Entity nodes error with "Node-RED custom integration needs to be installed in Home Assistant for this node to function correctly."

All package files appear to exist in custom_components/nodered
Node-Red was installed via Supervisor / Addon Store
hass-node-red was installed after the fact

Steps taken:
- Reinstalled hass-node-red from HACS
- Restarted homeassistant
- Restarted Node-red
- Rebooted the box
- All steps were followed on installation page for hass-node-red 
- No new entities are created or visible in Developer tab

**Comment by jb901** [comment]
I didnt install the configuration \ Integrations \ Node Red.  Sigh.

**Comment by wasyl00** [comment]
joined the club, wasted 2hrs of pointless reboots. witness me

**Comment by NiklasA95** [comment]
Same here. Not installed integration was the problem. Thanks for sharing your struggles.

**Comment by homemadestea58** [comment]
The integration doesn't show up for me.

**Comment by rkluijt2** [comment]
Same here. The only integeration in HACS I can find is Node-RED Companion. Even with that integration installed no new entities where created. Please advice what to do?

**Comment by wasyl00** [comment]
> Same here. The only integeration in HACS I can find is Node-RED Companion. Even with that integration installed no new entities where created. Please advice what to do?

After installing companion integration did you configured it? Go to integrations in HA Devices & Services and see if Nodered companion integration is configured.

**Comment by rkluijt2** [comment]
> > Same here. The only integeration in HACS I can find is Node-RED Companion. Even with that integration installed no new entities where created. Please advice what to do?
> 
> After installing companion integration did you configured it? Go to integrations in HA Devices & Services and see if Nodered companion integration is configured.

Well, feel stupid. After a reboot the integration appeared. Thanks. I can no see the created entity
