### ISSUE TITLE
Problem with Switch Entity

### ISSUE THREAD

**Issue by GrimmJok3r** [zachowj/hass-node-red#38]
Hi

First of all thank you for you work and nice add-on

HA version Home Assistant: 0.114.4
Node_Red version: 7.1.0
Node Red Intregration version: 0.4.4

## Describe the bug
The output points in Node red of the switch won't show any data when i add a Debug node to it.
When flipping the switch in HA the event-all and state change does show the switch being flipped.

If you look at the switch image attached it looks like some stuff is missing.

so i have a working situation especially handy concerning Lovelace :)

<img width="779" alt="Screenshot 2020-09-01 at 23 08 25" src="https://user-images.githubusercontent.com/31209358/91906452-7cc27100-eca8-11ea-8cbb-2c7bf004c966.png">

Thank you for your work

**Comment by fordarn** [comment]
Hi GrimmJok3r 
I have encountered the same issue which is causing the switch entity not to output on the output nodes and then is obviously not working did you find a work around?

**Comment by zachowj** [comment]
The switch entity currently doesn't do any output unless you use the `nodered.trigger` service in HA. Inside NR it functions the same as an NR switch node, it just redirects an input based on the switch state.
