### ISSUE TITLE
ha-state-node output on connect

### ISSUE THREAD

**Issue by melendezcr** [zachowj/hass-node-red#43]
Output on Connect

## Version of the custom_component
v0.4.4, Node-Red V7.2.6

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
The "Event: State" node of a custom component switch always send a payload on connect even if the "Output on Connect" option is unchecked.

## Debug log

```text

Add your logs here.

```

**Comment by zachowj** [comment]
This should be reported to [this](https://github.com/zachowj/node-red-contrib-home-assistant-websocket) repo.
