### ISSUE TITLE
Feature request: One node-red switch to multiple in HA (one switch to rule them all)

### ISSUE THREAD

**Issue by xppx99** [zachowj/hass-node-red#5]
Hello, 

First let me thank zachowj (and any other contributer that may have helped) for this  great work. This is really integrating node-red in HA. 

This is a feature request that fits my needs, I assume that may benefit other people too, but honestly I don't understand the complexity of this request and its feasibility (cost vs effort), and I understand if you devs decide against this feature. 

I use Node-Red with HA for many things. One of the things is to monitor the connectivity/availability of some devices IoT devices that are important in my system. 
I want to expose to HA a switch that would activate/deactivate multiple switchs so that I could deactivate the entire monitoring, because sometimes it is useful. 

Example 1 - monitor important devices: 
![image](https://user-images.githubusercontent.com/52202278/71356607-a7d1be00-257a-11ea-9683-d0aa68ceb589.png)

Example 2 - monitor air quality in the house
![image](https://user-images.githubusercontent.com/52202278/71356631-ba4bf780-257a-11ea-9964-a2e3af183f57.png)

What I have implemented is the input_bolean to allow this goal, but it would be much easier and cleaner to make that virtual switch available in Node-Red. 

Thanks!

**Comment by zachowj** [comment]
At the moment I don't see a feasible way to accomplished this. The switches are identified in HA by the node id from NR. So each switch in HA is a one to one reference to a node in NR.

You could expose each event node to HA and then make an input boolean in HA that when changed it sets all the event node switches to the same state as itself with a single call service. That's not much different from what you're doing now though.

**Comment by shbatm** [comment]
@xppx99 Just happened to be browsing and saw this -- I use a `group` in my Home Assistant config to give me single control of multiple NodeRED "Switches".

**Comment by xppx99** [comment]
Hello guys! So actually there is a way to do what I was asking about with the functionality already provided by this integration. 

The way is this: Exposing one of the switchs to act as "master switch", then replacing any "events: state" nodes by the improved "trigger: state" nodes, and then add a condition so that the msg are only propagated if the previously creater "master switch" is ON.

This way, everytime I deactivate the "master switch", every other trigger is also blocked, by the condition added. 
This as been working great!
