### ISSUE TITLE
Add service to pass data directly to a node in a flow

### ISSUE THREAD

**Issue by legomind** [zachowj/hass-node-red#6]
Almost exactly how webhooks work but with services as well.

My use case for this is pretty simple. I want to pass data from button click events in esphome via [homeassistant.service Action](https://esphome.io/components/api.html#homeassistant-service-action)

The idea is to have an esphome automation on the button double click event that will call a nodered service in home assistant, and that would in turn trigger the corresponding node in nodered.

**Comment by zachowj** [comment]
I am pretty sure you can accomplish this now using [homeassistant-event-action](https://esphome.io/components/api.html#homeassistant-event-action) in ESPHome then using an Events: all node listing for the event.

**Comment by legomind** [comment]
very clever. Somehow I didn't think of that.

Thanks!
