### ISSUE TITLE
[homeassistant.loader] No 'version' key in the manifest file for custom integration 'nodered'.

### ISSUE THREAD

**Issue by ve6rah** [zachowj/hass-node-red#61]
## Version of the custom_component
0.4.1

## Configuration

```yaml

2021-04-08 00:59:30 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'nodered'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'nodered'

```

## Describe the bug
manifest file needs updating for this integration to continue working with Home Assistant.

**Comment by zachowj** [comment]
This has already been addressed in the latest release. You need to update it.

**Comment by ve6rah** [comment]
According to home assistant, I am at the latest release.

**Comment by zachowj** [comment]
If you look at the [release section](https://github.com/zachowj/hass-node-red/releases/) on github the latest release is v0.4.5 you stated v0.4.1 as your version.

Not sure where in HA you see that v0.4.1 is the latest release.
