### ISSUE TITLE
NodeRED not in HA main menu

### ISSUE THREAD

**Issue by mielune** [zachowj/hass-node-red#62]
Hi all,

I just installed NodeRED throw HACS, restart server and clear my browser cache but NodeRED is not displayed in the HA main menu.

It seems to be loaded because I have this line in the HA logs:
```
2021-04-14 18:39:48 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

NodeRED plugin: 0.4.5
HA version 2021.1.5

Can someone help me to solve this issue ?

Best regards,

**Comment by zachowj** [comment]
This is just a companion integration to NR. You need to install Node-RED separately. 

<https://nodered.org/#get-started>

**Comment by svisso** [comment]
FYI: Please let me remark that I, too, have the above message in the log. But I installed Node Red some time ago and have never seen the msg until now, after I tried to install NodeRed Companion. This companion does not show up in Integrations, but there is the new warning in the log.
If you can give me a hint on how to make this Companion appear as an Integration? Would be highly apreciated.
Running core-2021.4.4
Node Red 8.2.0, Upgrade 8.2.1 pending
Thank you.

**Comment by zachowj** [comment]
@svisso did you do step 7 of the installation guide?

**Comment by mielune** [comment]
@zachowj  Ok I did'nt understand this, so ok :)
I'm working with HA inside a docker container (in a docker swarm stack).
Can I add NR has another container in the stack, if so, how to setup the NR url in the HA-plugin ?
This will be the best integration design, but any ideas are welcomes :)

KR

**Comment by svisso** [comment]
@zachowj Well, In the end, I found the integration. Some kind of a wording issue, I think, because you mention Node Red Companion but the integration's name is plain Node Red. My imagination and tech background first didn't suffice to fill the gap.
So, this looks ok, remains to be tested here.
Thank you.
