### ISSUE TITLE
Integration not working in 2021.6 / manual install

### ISSUE THREAD

**Issue by pricard32** [zachowj/hass-node-red#71]
The integration is not loaded by HA in version 2021.6 with a manual installation.

**Comment by charettepa** [comment]
Having same issue after upgrade to 2021.6.0

luckily I took a snapshot and was able to revert to 2021.5.5

All the log says is that it could not be loaded, any idea what the issue might be?

**Comment by pricard32** [comment]
I have no idea, I also revert to 21.5.5

**Comment by zachowj** [comment]
2021.6 requires at least version 0.4.5 installed otherwise HA will refuse to load it. What version do you have installed?

**Comment by pricard32** [comment]
I download the last one today, still not working.

**Comment by zachowj** [comment]
What do your HA logs show?

**Comment by pricard32** [comment]
Setup failed for nodered: Integration not found.

**Comment by zachowj** [comment]
That error would show when you don't have the custom component installed correctly

**Comment by pricard32** [comment]
No change between 21.5.5 and 21.6
And it work in 21.5.5

**Comment by charettepa** [comment]
I have the node-red companion from HACS
according to HACS I am at version 0.5.2

**Comment by charettepa** [comment]
OK, its now fixed for me
Not sure why, but in HACS it was no longer present as an installed integration
I forcefully re-installed it
This replaced the files in the custom components folder
HACS reported reboot needed
After reboot it was fine and there were newer files
I updated once more to HA 2021.6.0

ALL Good, Back in Business

Sorry for jumping the gun
Hope my findings helps others

**Comment by pricard32** [comment]
I don't use HACS, but will try to update the component in 21.5.5 and after this update HA to 21.6

**Comment by vpnobregahome** [comment]
Same problem here. After Last home assistant update, my node Red sensors stop working.

I cant see Node Red integration in list.
Any ideas to solve this?

**Comment by homemadestea58** [comment]
Have the same issue. Any help would be appreciated.

**Comment by homemadestea58** [comment]
@vpnobregahome I fixed my issue by forcefully refreshing my browser so that it updates the Integration list. I should really read the full installation manual in future as it mentions that there is a bug in HA where the UI isn't reloaded with the new integration list.

**Comment by pricard32** [comment]
What I did :

I revert back to 21.5.5, i've updated the custom component with the last one.
I update HA to 21.6
Éverythings work now
