### ISSUE TITLE
No "nodered.trigger" service after installation

### ISSUE THREAD

**Issue by frankitunes** [zachowj/hass-node-red#72]
custom_component : v0.5.2
nodered : 9.1.3
HA : core-2021.6.3

I have tried to install several times through HACS and manually but in both case I don't see the service "nodered.trigger". I got the node-red companion integration but there is no entity linked to it.

![image](https://user-images.githubusercontent.com/35428340/121300426-1b929280-c8f7-11eb-8ab1-6b0383c13b76.png)

What did I do the wrong way ? Thanks a lot for your help.

**Comment by zachowj** [comment]
The service isn't created until there's a switch entity created by NR in HA.

**Comment by frankitunes** [comment]
Waow so easy, thanks a lot @zachowj!
