### ISSUE TITLE
New sensor properties: state_class & last_reset

### ISSUE THREAD

**Issue by alexdelprete** [zachowj/hass-node-red#78]
Hi,

in recent HA releases, in order to support long-term statistics, devs have updated sensors' properties, introducing `last_reset `and `state_class`: https://developers.home-assistant.io/docs/core/entity/sensor/

![image](https://user-images.githubusercontent.com/7027842/133829291-45efa571-c216-450f-92cb-e0c9d157ec62.png)
![image](https://user-images.githubusercontent.com/7027842/133829304-01f39856-2628-4196-b878-c67fa20262e7.png)

Could you please update the component adding those two properties? They are needed in particular for the new Energy Integration. I use node-red to pull data from my energy meters, as a workaround I added `state_class `as an attribute key, but it would be nice to have it as a default property like `device_class` in the Home Assistant Config section.

![image](https://user-images.githubusercontent.com/7027842/133830086-5d55ea08-7d2f-412a-89eb-4f566ba3c118.png)

Thanks a lot for your work.

Alessandro

**Comment by alexdelprete** [comment]
@zachowj Jason, from a quick look at the code, in order to add those two properties, only `__init__.py` has to be updated right?
If you can confirm, I can try to submit a PR tomorrow.

**Comment by zachowj** [comment]
They should be added to the sensor class, in sensor.py, as I believe they only apply to sensors.

**Comment by alexdelprete** [comment]
For another component, I added `state_class` like this:

```python
from homeassistant.components.sensor import SensorEntity

class ABBPowerOnePVISunSpecSensor(SensorEntity):
    """Representation of an ABB SunSpec Modbus sensor."""

    def __init__(
        self, platform_name, hub, device_info, name, key, unit, icon, device_class, state_class
    ):
        """Initialize the sensor."""
        self._platform_name = platform_name
        self._hub = hub
        self._device_info = device_info
        self._name = name
        self._key = key
        self._unit_of_measurement = unit
        self._icon = icon
        self._device_class = device_class
        self._state_class = state_class

    @property
    def device_class(self):
        """Return the sensor device_class."""
        return self._device_class

    @property
    def state_class(self):
        """Return the sensor state_class."""
        return self._state_class
```

But the code I see in sensor.py is much different. I guess I'll wait for you to implement it. :)

**Comment by zachowj** [comment]
Currently, how config properties are implemented it's not possible to update them from input into an entity node. Would this be bad for `last_reset`? You would have to manually edit the node and deploy for this value to be changed.

**Comment by alexdelprete** [comment]
> Would this be bad for `last_reset`? You would have to manually edit the node and deploy for this value to be changed.

Well, right now that's how I'm making it work: editing the node and adding the state_class as an attribute, then deploy. I expect the only difference to be, if implemented, that we find state_class in the optional Home Assistant Config" section, instead of the Attributes section:

![image](https://user-images.githubusercontent.com/7027842/145357715-2250f1c0-52ab-4ad3-b1e3-f292482349df.png)

So it wouldn't change anything...if I understood correctly your post.

**Comment by alexdelprete** [comment]
Thanks for this Jason. Can I test it installing version "main" of the custom component?

**Comment by alexdelprete** [comment]
Updated everything. Seems to be working...I'll monitor the sensors...

**Comment by Jpsy** [comment]
In the release notes of 1.0.0 I read:

> Using attributes for state_class and last_reset on the entity node will no longer show these properties in Home Assistant. There are now config fields for these properties.

But I cant find any new config fields after update from 0.5.4 to 1.0.1.
Where should I move the attribute `state_class` to in the following sensor?

![image](https://user-images.githubusercontent.com/1806058/147454787-43b26438-0387-42dd-b206-23d7c679f62b.png)

**Comment by alexdelprete** [comment]
> But I cant find any new config fields after update from 0.5.4 to 1.0.1. Where should I move the attribute `state_class` to in the following sensor?

Like Jason wrote [here](https://github.com/zachowj/hass-node-red/issues/78#issuecomment-997962780): you need to update HA nodes to v0.40.0, from the NR "Manage Palette".

![image](https://user-images.githubusercontent.com/7027842/147455136-775732bd-ccad-4986-92e6-35ee5107455a.png)

**Comment by Jpsy** [comment]
Oh, thanks for the swift answer! Will do.
