### ISSUE TITLE
No new integration "Node-red"

### ISSUE THREAD

**Issue by Dohnalradek** [zachowj/hass-node-red#8]
I follow your guide, createn new folder nodered (subfolder of custom_components), cope there all files and restart Hass.io. But when I go to Configuration -> Integrations -> + there isnt option nodered.

Im using Hass.io and Node-red v.6.0.0

**Comment by Dohnalradek** [comment]
I follow your guide, createn new folder **nodered** (subfolder of **custom_components**), cope there all files and restart Hass.io. But when I go to Configuration -> Integrations -> + there isnt optin **nodered**

**Comment by zachowj** [comment]
Do the Home Assistant logs show the component loading?

`WARNING (MainThread) [homeassistant.loader] You are using a custom integration for nodered which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.`

**Comment by Dohnalradek** [comment]
No, there's nothing in Hass.io log.
Do I add something to **configuration.yaml**?

**Comment by tiagofreire-pt** [comment]
I have this same issue, no matter the restarts.

HA 0.105.2.
Lastest Node-red Add-on.

**Comment by tiagofreire-pt** [comment]
@Dohnalradek , do you mind re-opening this issue, please?

**Comment by zachowj** [comment]
@tiagofreire-pt does #11 solve your issue?

**Comment by tiagofreire-pt** [comment]
@zachowj , seems stable for now.
