### ISSUE TITLE
Ghost entities, not in flow.json, how to delete?

### ISSUE THREAD

**Issue by Swiftnesses** [zachowj/hass-node-red#81]
I've tried literally everything from manually deleting them from the HA entities file, to deleting the integration.

My flows.json only has one 'ha-entity' type node, so I have no idea where all these switches are coming from...?

Any idea how I can stop them appearing?
<img width="1046" alt="Screenshot 2021-10-03 at 19 10 36" src="https://user-images.githubusercontent.com/1001877/135766262-47b69503-f1d2-485b-a72d-02a4ecf51e8b.png">
?

**Comment by zachowj** [comment]
Do you have any event nodes exposed HA? events: state, poll state, or trigger: state nodes?

**Comment by Swiftnesses** [comment]
<img width="384" alt="Screenshot 2021-10-03 at 19 26 39" src="https://user-images.githubusercontent.com/1001877/135766704-0826364f-a1d2-4b56-946d-d9f7b5af0849.png">
Like these? If so, yes, lots of them... I have around 30 flow tabs, hundreds of flows...

**Comment by Swiftnesses** [comment]
Argh, I just noticed the check box "expose to home assistant" - not seen this before.

I'll check them, is there a quick way to do this?

**Comment by zachowj** [comment]
With the `Expose to Home Assistant` Checked?

![image](https://user-imagesgithubusercontent.com/37859597/135766769-d2295856-2c09-43ef-84f8-d1a36596be21.png)

You can find the nodes that are creating the entities by using the Find feature in NR. Type in the first 3-4 characters from the entity after `nodered_adc5b4c38...`. Search for adc54

**Comment by Swiftnesses** [comment]
<img width="1157" alt="Screenshot 2021-10-03 at 19 32 21" src="https://user-images.githubusercontent.com/1001877/135766891-4ae7c826-1b77-4bfc-9fb9-45f6bb63e0fd.png">
Got them, it looks like the new device trigger node causes this...

**Comment by zachowj** [comment]
Yes, device nodes are automatically exposed to HA because they use HA device automation to process the request.

**Comment by Swiftnesses** [comment]
Okay, it's a little confusing as they're not strictly used by the companion or the entity node, will this behaviour change in the future?

**Comment by zachowj** [comment]
Can you explain a little more about what is confusing about them? They work the same way the events nodes do except that they are always exposed to HA.  Which gives them the ability to be enabled/disabled and triggered from HA.

I don't see this changing in the future.

Also, if you fill in the name field in the HA config box before you first deploy the node it will attempt to create the entity id with that name and not the node id as the entity id.
