### ISSUE TITLE
Migrate Home Assistant webhook to NodeRed

### ISSUE THREAD

**Issue by selmaohneh** [zachowj/hass-node-red#83]
## Version of the custom_component
v0.5.2

More of a question, but here we go:

I have an existing webhook that is used as a trigger for a native Home Assistant automation. It was automatically created when I created that automation via the Home Assistant automation UI.

Now, finally having the fancy NodeRed Companion installed, I want to migrate that webhook to NodeRed. But this is where I fail. 

What do I need to enter inside ID of the webhook node? I tried the following:

![image](https://user-images.githubusercontent.com/29881939/143029908-fed0cd00-3cb6-4cff-b474-ca5c1e19a143.png)

and this one (complete URL and only the trailing ID):

![image](https://user-images.githubusercontent.com/29881939/143030095-29326109-91d5-470b-9774-916de8c47ae8.png)

The still existing automations shows me that the webhook is triggered every 60s, but a debug node after the webhook node stays empty. :-(

What am I doing wrong?

Thanks in advance!

**Comment by zachowj** [comment]
Remove the HA automation webhook and restart HA. Then the webhook in NR should start working. Webhooks have to have unique ids in both HA and NR.

**Comment by selmaohneh** [comment]
So if I recreate the webhook via the NodeRed node with the same name, the webhook URL will be the same again?

This is important since I do not have access to the client calling the webhook very often and I am not able to modify the URL on client side soon...

**Comment by zachowj** [comment]
Yes, if the webhook Id is the same in NR as it was in HA it will work.

**Comment by selmaohneh** [comment]
Mhm - I tried.
Although I gave the webhook the same ID, the provided invocation URL differs from the previous one. 👎 
So now I'm sitting here with a broken sensor until I am able to modify the URL on the remote client. :-/

Thanks anyway!
