### ISSUE TITLE
Poll state and change state nodes returns unavailable on 0.5.3 & 0.5.4

### ISSUE THREAD

**Issue by Baael** [zachowj/hass-node-red#86]
## Describe the bug
Since I updated to version 0.5.3 or 0.5.4 all the poll state and change state nodes are returning `unavailable` on all sensors. Downgrading to 0.5.2 solved a problem. 

## Debug log
Nothing in logs.

**Comment by zachowj** [comment]
What version of HA you running?

**Comment by 1192410** [comment]
for me the node-red Web UI is not reachable and seems to be stuck in an endless loop. If I disable node-red companion everything works fine. 

companion v5.4 
Hassio core-2021.11.5

**Comment by Cafun** [comment]
+1 for the crashing of Node-Red

**Comment by zachowj** [comment]
@Cafun what version of the NR nodes are you running?

**Comment by 1192410** [comment]
Current version: 10.2.0 is the version im running

**Comment by zachowj** [comment]
> Current version: 10.2.0 is the version I'm running

That's the add-on version. What's the version of the node-red-contrib-home-assiatant-websocker package?

**Comment by Cafun** [comment]
> @Cafun what version of the NR nodes are you running?

Hi! I've updated all pallets and now everything is working again.

**Comment by 1192410** [comment]
> > Current version: 10.2.0 is the version I'm running
> 
> That's the add-on version. What's the version of the node-red-contrib-home-assiatant-websocker package?

0.5.4

**Comment by 1192410** [comment]
I have also looked at all the sensors ... I had wrong device classes in two of them. After deleting those, everything worked fine.

**Comment by Baael** [comment]
> What version of HA are you running?

Home Assistant 2021.11.0
