### ISSUE TITLE
Supervisor/nodered/log only shows last 2 minutes 

### ISSUE THREAD

**Issue by guenter-ms** [zachowj/hass-node-red#87]
Hello,

the log file in the nodered add-on only shows the last 2 minutes. The complete log file is not visible or can be found in the file system.

## Configuration.yaml:

![Bildschirmfoto 2021-12-04 um 15 59 09](https://user-images.githubusercontent.com/6253315/144714244-97432441-476c-4024-9bbd-e0b3863a1e3e.jpg)

## Describe the bug
The system log entries from nodered cannot be found if they are older than 2 minutes. See screenshots, only from 15:31:30 to 15:32:20 messages are displayed. 

![begin](https://user-images.githubusercontent.com/6253315/144713602-7cea14d7-f98f-4a18-a957-e9ffc3a9d517.jpg)

![end](https://user-images.githubusercontent.com/6253315/144713607-c6667034-5f05-4214-8d4c-635e3804d3e9.jpg)

## Debug log

I have enabled the logger, see configuration.yaml before. This leads to a big home-assistant.log. But the messages in the 2-minute add-on log are not in there.

Below some more input.
Can u help getting the complete nodered log?

Thank you!

![Bildschirmfoto 2021-12-04 um 15 52 49](https://user-images.githubusercontent.com/6253315/144714134-a91b790e-bbf5-42ad-a615-9c10aa27f435.jpg)
![Bildschirmfoto 2021-12-04 um 15 52 22](https://user-images.githubusercontent.com/6253315/144714166-d22560f1-77ee-44cc-aa14-f62c047da7bb.jpg)

**Comment by zachowj** [comment]
This is a repo for the NR custom integration you probably want the add-on repo

https://github.com/hassio-addons/addon-node-red
