### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by ei23fxg** [zachowj/hass-node-red#91]
[Feature Request]
I guess you already know:
[Home Assistant has a new Button-Feature!](https://www.home-assistant.io/blog/2021/12/11/release-202112/#the-button-entity)
Would be nice to also make use of it in an entity from NodeRED!

(And -> Thanks a lot for your work!)

**Comment by akmolina28** [comment]
How does this work? Can you create a node and expose it to HA as a button entity? I updated but I can't figure it out. Thanks!

**Comment by zachowj** [comment]
It will be a new node in the next release of https://github.com/zachowj/node-red-contrib-home-assistant-websocket
