### ISSUE TITLE
ha.entity's unit of measurement is not honored in home assistant

### ISSUE THREAD

**Issue by b3nj1** [zachowj/hass-node-red#95]
## Version of the custom_component
Latest: v1.0.1

## Configuration

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13173423/147771496-9563810c-5dd8-42ee-b674-d01163e6a0bb.png">

## Describe the bug

With v0.5.4, the sensor showed up in Home Assistant with the correct temperature. Since I have my HA configured for imperial, the  would then be converted to °F for display.

With v1.0.1, the sensor shows up wrong. It looks like it has been converted CtoF twice: 20C -> 69F; 69"C" -> 156"F"

<img width="337" alt="image" src="https://user-images.githubusercontent.com/13173423/147772148-949aee5e-977c-4fbd-8561-8d9f505b76f7.png">

<img width="474" alt="image" src="https://user-images.githubusercontent.com/13173423/147772167-c8d3dacd-8ae4-4278-8df5-3535d969028a.png">

**Comment by b3nj1** [comment]
I have a theory that the problem is that native_unit_of_measurement is not being advertised. 
https://developers.home-assistant.io/blog/2021/08/12/sensor_temperature_conversion

**Comment by zachowj** [comment]
With 1.0 I switched the sensor entity to use native value. Is your value that you're sending the entity node in C or F? I believe with native it expects the unit type to be what the value is and not what you want it to display. If this is the case I'll need to add that to the release notes.

**Comment by b3nj1** [comment]
In my case , the sensor entity node is sending C and is using C as its unit, so it is "what the value is" not what I "want tit to display". So, that doesn't seem to be it.

In HA, I don't have any customizations on the sensor. I globally have imperial as my default. In HA, the sensor shows up with unit of F.

The values/units are shown above in the screen grabs both in Node-Red and in HA devices in case my description here isn't clear.

It seems other integrations are seeing similar bad temps: https://github.com/home-assistant/core/issues/61163

**Comment by b3nj1** [comment]
I noticed that my MQTT Sensor which is in C works, so I looked at their code. The MQTT Sensor code was changed to report "native" properties back when this was introduced. My stab in the dark is that would help :) 


```
# git diff 2021.8.8 2021.9.0 homeassistant/components/mqtt/sensor.py | tail -20
                 "topic": self._config[CONF_LAST_RESET_TOPIC],
                 "msg_callback": last_reset_message_received,
@@ -214,7 +258,7 @@ class MqttSensor(MqttEntity, SensorEntity):
         self.async_write_ha_state()
 
     @property
-    def unit_of_measurement(self):
+    def native_unit_of_measurement(self):
         """Return the unit this state is expressed in."""
         return self._config.get(CONF_UNIT_OF_MEASUREMENT)
 
@@ -224,7 +268,7 @@ class MqttSensor(MqttEntity, SensorEntity):
         return self._config[CONF_FORCE_UPDATE]
 
     @property
-    def state(self):
+    def native_value(self):
         """Return the state of the entity."""
         return self._state
```

**Comment by b3nj1** [comment]
Should this be native_unit_of_measurement?

https://github.com/zachowj/hass-node-red/blob/0763aec6d8dbbb31fba785278205cca59c25c101/custom_components/nodered/__init__.py#L141

**Comment by zachowj** [comment]
> Should this be native_unit_of_measurement?

The sensor should be using the one from HA `SensorEntity`

https://github.com/home-assistant/core/blob/6725e4033c418ee2245eeb52796219cddbc23661/homeassistant/components/sensor/__init__.py#L346-L362

I'll take a closer look at this.

**Comment by zachowj** [comment]
@b3nj1 let me know if that fixes it for you. If not reopen the issue.
